all :   prog03 prog05 prog06 prog07 prog08 prog09 prog10 prog11

#prog01 : how-to-pass-reference-variable-to-thread.cpp
#	g++ -o prog01 how-to-pass-reference-variable-to-thread.cpp  -std=c++14

#prog02 : mutex-semaphorse.cpp
#	g++ -o prog02 mutex-semaphorse.cpp -std=c++14

prog03 : swap-number-in-thread.cpp
	g++ -o prog03 swap-number-in-thread.cpp -std=c++14

#prog04 : thread-creation.cpp
#	g++ -o prog04 thread-creation.cpp -std=c++14

prog05 : modified_thread_creation.cpp
	g++ -o prog05 modified_thread_creation.cpp -std=c++14

prog06 : join-thread.cpp
	g++ -o prog06 join-thread.cpp -std=c++14

prog07 : vector-of-std-thread.cpp
	g++ -o prog07 vector-of-std-thread.cpp -std=c++14

prog08 : conditional-variable-producer-consumer.cpp
	g++ -o prog08 conditional-variable-producer-consumer.cpp -std=c++14

prog09 : producer-consumer-condition_variable.cpp
	g++ -o prog09 producer-consumer-condition_variable.cpp -std=c++14

prog10 : producer-consumer-semaphorse.cpp
	g++ -o prog10 producer-consumer-semaphorse.cpp -lpthread -fpermissive -std=c++14

prog11 : future-promise.cpp
	g++ -o prog11 future-promise.cpp -std=c++14