#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# name: led-service
# Last modified: vijay.kumar@smartron.com,nagendra@smartron.com, 14/06/2018 
#====================================================================#
. /tmp/updated
START=82
STOP=15
USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done
	logger -p user.notice "LED service starting..."
	procd_open_instance
        procd_set_param command led-server
	procd_set_param respawn
        procd_close_instance
	logger -p user.crit "[LED]: LED service started"

}

stop_service() {

	killall led-server
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[LED]: LED service stopped"
	else 
		logger -p user.crit "[LED]: No LED service to stop"
	fi
}
