#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.1
# Last modified:nagendra@smartron.com 25/07/2018
#====================================================================#
. /tmp/updated

START=87
USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done
	logger -p user.notice "[FOTA]: Fota Update service initiated"
        procd_open_instance
        procd_set_param command fota_update
        procd_close_instance
	logger -p user.crit "[FOTA]: Fota Update service started"
}

