#!/bin/sh /etc/rc.common
#=====================================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 22/05/2018
#=====================================================================================#

. /tmp/updated

START=80

USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done

	logger -p user.notice "Service Manager starting..."
	procd_open_instance
	procd_set_param command /usr/bin/sm_app
	procd_set_param respawn
	procd_close_instance
	logger -p user.crit "[SM]: Service Manager service started"
}

stop_service() {
	killall sm_app
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[SM]: Service Manager service stopped"
	else 
		logger -p user.crit "[SM]: No Service Manager service to stop"
	fi
}
