pcm.!default {
	type plug
	slave.pcm "dmixer"
	ttable {
    	# Copy both input channels to output channel 0 (Left).
    	0.0 0.5
    	1.0 0.5
    	# Copy both input channels to output channel 1 (Right).
    	0.1 0.5
    	1.1 0.5
	}
}
pcm.!default
{
    type asym
    playback.pcm
    {
        type plug
        slave.pcm "dmixer"
    }
    capture.pcm
    {
        type plug
        slave.pcm "hw:1,0"
    }
}

pcm.dmixer  {
    type dmix
    ipc_key 1025
    slave {
        pcm "hw:0,0"
        period_time 0
        period_size 4096
        buffer_size 16384
        periods 128
        rate 48000
    }
}
ctl.dmixer {
        type hw
        card 0
}
