#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 14/06/2018
#====================================================================#
START=30

USE_PROCD=1

start_service() {

        procd_open_instance
        procd_set_param command check_tz
        procd_close_instance
}
