# Configuration file for Z-Wave Scenes and Security Scenes
#
#
# The format is as follows:
#
# [GROUP NAME]
# 	key=value
# [GROUP NAME]
#	key=value
#
# Group names, keys and values are case sensitive
#

# Security Scene Email notification settings
# The key 'sender' is ignored when SMTP is enabled.
[SECURITY SCENE NOTIFICATION EMAIL]
enable=true
sender=z-wavesupport@sigmadesigns.com

# Security Scene SMS notification settings
# The gateway will be used to send SMS using <number>@<gateway> format
# The number would given in a Security Scene while gatway must be defined below.
# The key 'sender' is ignored when SMTP is enabled.
[SECURITY SCENE NOTIFICATION SMS]
enable=true
sender=z-wavesupport@sigmadesigns.com
gateway=onewaysms.asia

# SMTP Server settings for email
[SMTP]
enable=true
auth_enable=true
username=ttestsmpt@gmail.com
password=_0000000
server_hostname=smtp.gmail.com
server_port=587
secure_method=tls

# Common settings
[COMMON]
# zwave_same_report_ignore_interval is the interval (in seconds) between the two consecutive exactly same device reports allowed be a valid Event trigger.
zwave_same_report_ignore_interval=600
