all : prog01 

prog01 : example_1.cpp
	g++ -o prog01 example_1.cpp -lsqlite3 -std=c++14

#prog02 : standared-templarte-library-functor.cpp
#	g++ -o prog02 standared-templarte-library-functor.cpp -std=c++14