all : prog01 prog02

prog01 : lambda-expression.cpp
	g++ -o prog01 lambda-expression.cpp -std=c++14

prog02 : standared-templarte-library-functor.cpp
	g++ -o prog02 standared-templarte-library-functor.cpp -std=c++14