FW_UPDATE_STATUS
DEVICE_NAME
TRONX_URL
HOME_TOKEN
ACCOUNT_TOKEN
DEVICE_REGISTRATION_STATUS
MA_TRONX_TIMEOUT
MA_BT_TIMEOUT
SOCKET_IO_RESOURCE
MA_LISTEN_PORT
MA_CONTROL_TIMEOUT
MA_QWRAP_CONNECT_TIMEOUT
MA_QWRAP_RESET_TIMEOUT
MA_FACTORY_RESET_TOKEN
MA_EBLR_SSID
MA_EBLR_PASSWORD
MA_EBLR_ENCRYPTION
MA_EBLR_FLAG
MA_EXCLUSION_TIMEOUT
MA_TTS_TIMEOUT
MA_ROUTER_SSID
MA_ROUTER_PASSWORD
MA_ROUTER_ENCRYPTION
MA_ROUTER_FLAG
BT_DEVICE_LIMIT
DM_SCENE_DEVICES_LIMIT
DM_SCENE_SONGS_LIMIT
DM_RULE_DEVICES_LIMIT
DM_RULE_SONGS_LIMIT
DM_DISCOVERY_TIMEOUT
DM_CONTROL_TIMEOUT
DM_REMOVE_TIMEOUT
DM_STACK_CHECK
DM_ZMQ_SERVER
DM_SS_ZMQ_CLIENT
DM_MA_ZMQ_CLIENT
DM_VA_ZMQ_CLIENT
ZB_SHORT_POLL_TIME
ZB_LONG_POLL_TIME
ZB_SEND_ME_A_REPORT_TIME
ZB_DISC_DM_MSG_ID
ZB_SND_DM_MSG_ID
ZB_RCV_DM_MSG_ID
ZB_NOD_DISC_PROG
LED_VOLUME_TIMEOUT
LED_VOICE_VOLUME_TIMEOUT
LED_MIC_MUTE_TIMEOUT
LED_ERROR_TIMEOUT
LED_ALARM_TIMEOUT
LED_DEVICE_CONNECTED_TIMEOUT
LED_DEVICE_DISCOVERY_TIMEOUT
LED_QUERY_RESPONSE_TIMEOUT
LED_QUERY_PROCESSING_TIMEOUT
LED_SETUP_MODE_TIMEOUT
LED_BT_CONNECTED_TIMEOUT
LED_BT_DISCOVERY_TIMEOUT
LED_DEAFAULT_TIMEOUT
LED_OFFLINE_TIMEOUT
LED_MICMUTEOFF_TIMEOUT
LOG_MASK
LOG_LEVEL
VA_TRONX_URI
VA_NOQUERY_THR
VA_WORD_SPACE_THR
VA_VAD_BACKOFF
VA_VAD_HOLD_OVER
VA_VAD_TRAIL_SILENCE
VA_VAD_MIN_DURATION
VA_VAD_THR
VA_VAD_SKIP_SAMP
VA_VAD_LEAD_SILENCE
VA_SEARCH_POINT
VA_PRIM_SESS_VOL
VA_SEC_SESS_VOL
VA_PRIM_ALARM_VOL
VA_ALARM_COUNT
VA_REMINDER_COUNT
VA_RULE_COUNT
VA_BUTTON_VOL00
VA_BUTTON_VOL01
VA_BUTTON_VOL02
VA_BUTTON_VOL03
VA_BUTTON_VOL04
VA_BUTTON_VOL05
VA_BUTTON_VOL06
VA_BUTTON_VOL07
VA_BUTTON_VOL08
VA_BUTTON_VOL09
VA_BUTTON_VOL10
VA_CURL_BE_RESP_TIMEOUT
VA_CURL_PINT_RESP_TIMEOUT
CURL_CONNECT_TIMEOUT
CURL_TCP_KEEPALIVE
CURL_TCP_KEEPIDLE
CURL_TCP_KEEPINTVL
MA_FOTA_TIMEOUT
IOT_RESET_FLAG
ZB_IOT_RESET
MQTT_ZMQ_SERVER_ADDR
ALEXA_REGISTRATION_STATUS
SKIP_ALEXA_REGISTRATION
