#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 11/05/2018
#====================================================================#

. /tmp/updated

START=86

USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done
	logger -p user.notice "[MA]: web socket is starting."
	procd_open_instance
	procd_set_param command Web_Socket.py
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-20}
	procd_close_instance
	logger -p user.notice "[MA]: web socket is started"
}
stop_service() {
	logger -p user.notice "web socket is stopped"
	kill -9 `ps | grep Web_Socket | grep -v grep | awk '{print $1}'`
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[MA]: web socket service stopped"
	else 
		logger -p user.crit "[MA]: No web socket service to stop"
	fi
}
