#!/bin/sh /etc/rc.common
#=====================================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 17/07/2018
#=====================================================================================#

. /tmp/updated

START=80

USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done

	logger -p user.notice "Device profile service  starting..."
	procd_open_instance
	procd_set_param command /usr/bin/MA_boottime_update.py
	procd_close_instance
	logger -p user.crit "[MA]: Device profile service started"
}

stop_service() {

	kill -9 `ps | grep MA_boottime_update | grep -v grep | awk '{print $1}'`
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[MA]: Device profile service stopped"
	else 
		logger -p user.crit "[MA]: No Device profile service to stop"
	fi
}
