#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 11/05/2018
#====================================================================#

. /tmp/updated

START=81

USE_PROCD=1

start_service() {
	
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done
	
	logger -p user.notice "[MA]: Mobile agent is starting."
	procd_open_instance
	procd_set_param command /usr/bin/Mobile_Agent.py
	procd_set_param respawn
	procd_close_instance
	logger -p user.crit "[MA]: Mobile Agent service started."
}
stop_service() {

	kill -9 `ps | grep Mobile_Agent | grep -v grep | awk '{print $1}'`
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[MA]: Mobile Agent service stopped"
	else 
		logger -p user.crit "[MA]: No Mobile Agent service to stop"
	fi
}
