#!/bin/sh /etc/rc.common
#=====================================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.2
# Last modified: nagendra@smartron.com, janardhanachari.kella@smartron.com, 02/04/2018
#=====================================================================================#

. /tmp/updated

START=86

USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done

	logger -p user.notice "[CRON]: Cron Handle is starting"
	procd_open_instance
	procd_set_param command /usr/bin/cron_handler
	procd_set_param respawn
	procd_close_instance
	logger -p user.crit "[CRON]: Cron Handle service started"
}

stop_service() {
	killall cron_handler
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[CRON]: Cron Handle service stopped"
	else 
		logger -p user.crit "[CRON]: No Cron Handle service to stop"
	fi
}
