#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.2
# Last modified: janardhanachari.kell@smartron.com,nagendra@smartron.com 14/06/2018
#====================================================================#
. /tmp/updated
START=81
STOP=21
USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done
	logger -p user.notice "[SSDP]: SSDP service starting"
        procd_open_instance
        procd_set_param command ssdp_server
	procd_set_param respawn
        procd_close_instance
	logger -p user.crit "[SSDP]: SSDP service started"
}

stop_service() {
	killall ssdp_server
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[SSDP]: SSDP service stopped"
	else 
		logger -p user.crit "[SSDP]: No SSDP service to stop"
	fi
}

