#!/bin/sh

autoscan
mv configure.scan configure.ac
autoconf
autoheader

grep -q 'AM_INIT_AUTOMAKE' configure.ac || \
    sed -i '/AC_INIT(\[FULL-PACKAGE-NAME\], \[VERSION\], \[BUG-REPORT-ADDRESS\])/ a\
AM_INIT_AUTOMAKE(\[FULL-PACKAGE-NAME\], \[VERSION\])\
AM_INIT_AUTOMAKE(\[subdir-objects\])\
' configure.ac

grep -q 'AC_CONFIG_MACRO_DIR(\[m4\])' configure.ac || \
    sed -i '/AM_INIT_AUTOMAKE(\[subdir-objects\])/ a\
AC_CONFIG_MACRO_DIR(\[m4\])' configure.ac

grep -q 'AM_PROG_CC_C_O' configure.ac || \
    sed -i '/AC_PROG_MKDIR_P/ a\
AM_PROG_CC_C_O' configure.ac

grep -q 'FIND_LIBFCGI' configure.ac || \
    sed -i '/# Checks for libraries\./ a\
FIND_HCAPI_SECURITY\
AC_SUBST(HCAPI_SECURITY)\
FIND_OPENSSL\
AC_SUBST(OPENSSL_INC)\
AC_SUBST(OPENSSL_LIB)\
FIND_ZWARE_TYPE\
FIND_HCAPI\
AC_SUBST(HCAPI_INC)\
AC_SUBST(HCAPI_LIB_ZWAPI)\
AC_SUBST(HCAPI_LIB_HCAPI)\
AC_SUBST(HCAPI_SECURITY_INC_FLAGS)\
AC_SUBST(HCAPI_SECURITY_LDFLAGS)\
AC_SUBST(HCAPI_SECURITY_LIBS)\
FIND_LIBCONFIG\
AC_SUBST(LIBCONFIG_INC)\
AC_SUBST(LIBCONFIG_LIB)\
FIND_SIMCLIST\
AC_SUBST(SIMCLIST_INC)\
AC_SUBST(SIMCLIST_LIB)\
FIND_LDAP\
AC_SUBST(LDAP_INC)\
AC_SUBST(LDAP_LIB)\
FIND_APR\
AC_SUBST(APR_CONFIG)\
FIND_APR_UTIL\
AC_SUBST(APR_UTIL_CONFIG)\
FIND_AVRO\
AC_SUBST(AVRO_PATH)\
FIND_LIBFFI\
AC_SUBST(LIBFFI_CFLAGS)\
AC_SUBST(LIBFFI_LIBS)\
FIND_ZLIB\
AC_SUBST(ZLIB_CFLAGS)\
AC_SUBST(ZLIB_LIBS)\
FIND_GLIB\
AC_SUBST(GLIB_CFLAGS)\
AC_SUBST(GLIB_LIBS)\
FIND_EXPAT\
AC_SUBST(EXPAT_CFLAGS)\
AC_SUBST(EXPAT_LIBS)\
FIND_UDUNITS\
AC_SUBST(UDUNITS_CFLAGS)\
AC_SUBST(UDUNITS_LIBS)\
FIND_LIBESMTP\
AC_SUBST(LIBESMTP_CFLAGS)\
AC_SUBST(LIBESMTP_LIBS)\
FIND_LIBZWSCENE\
AC_SUBST(LIBZWSCENE_CFLAGS)\
AC_SUBST(LIBZWSCENE_LIBS)\
FIND_SQLITE\
AC_SUBST(SQLITE_INC)\
AC_SUBST(SQLITE_LIB)\
FIND_CJSON64\
AC_SUBST(CJSON64_INC)\
AC_SUBST(CJSON64_LIB)\
FIND_CURL\
AC_SUBST(CURL_INC)\
AC_SUBST(CURL_LIB)\
#FIND_LIBFCGI\
#AC_SUBST(LIBFCGI_INC)\
#AC_SUBST(LIBFCGI_LIB)\
' configure.ac

aclocal

touch COPYING INSTALL NEWS README AUTHORS ChangeLog
automake -a -c

autoreconf

