#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (C) 2011 OpenWrt.org
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 14/06/2018
#====================================================================#
. /tmp/updated
START=96
STOP=20
USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done

	logger -p user.notice "Zwave service starting"
	procd_open_instance
	procd_set_param command /exe_dir/zwave_init
	procd_set_param respawn
	procd_close_instance
	logger -p user.crit "[ZW]: Zwave service started"
}

stop_service() {
	killall zwave_app

	if [ "$?" = "0" ] ; then
		logger -p user.crit "[ZW]: Zwave service stopped"
	else 
		logger -p user.crit "[ZW]: No Zwave service to stop"
	fi
}
