#!/bin/sh

#logger -p user.notice "before changing directory for zwave service in separate script"
cd /exe_dir/

var=`$(ps | grep "{zwave_init}" | awk '{print $5}'| grep '{zwave_init}')`

if [ "$(ps | grep "{zwave_init}" | awk '{print $5}'| grep '{zwave_init}')" != "{zwave_app}" ]
then

#    logger -p user.notice "in if check zwave_app $var"
    zwave_app
fi
