#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (C) 2011 OpenWrt.org
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 11/05/2018
#====================================================================#

START=83

boot() {
    mkdir -p /var
    mkdir -p /var/log
    mkdir -p /var/log/zweb
    apachectl start
}

