/** @copyright
© 2014 SIGMA DESIGNS, INC. THIS IS AN UNPUBLISHED WORK PROTECTED BY SIGMA 
DESIGNS, INC. AS A TRADE SECRET, AND IS NOT TO BE USED OR DISCLOSED EXCEPT AS 
PROVIDED Z-WAVE CONTROLLER DEVELOPMENT KIT LIMITED LICENSE AGREEMENT. ALL 
RIGHTS RESERVED.
@par
NOTICE: ALL INFORMATION CONTAINED HEREIN IS CONFIDENTIAL AND/OR PROPRIETARY TO 
SIGMA DESIGNS AND MAY BE COVERED BY U.S. AND FOREIGN PATENTS, PATENTS IN 
PROCESS, AND ARE PROTECTED BY TRADE SECRET OR COPYRIGHT LAW. DISSEMINATION OR 
REPRODUCTION OF THE SOURCE CODE CONTAINED HEREIN IS EXPRESSLY FORBIDDEN TO 
ANYONE EXCEPT LICENSEES OF SIGMA DESIGNS  WHO HAVE EXECUTED A SIGMA DESIGNS’ 
Z-WAVE CONTROLLER DEVELOPMENT KIT LIMITED LICENSE AGREEMENT. THE COPYRIGHT 
NOTICE ABOVE IS NOT EVIDENCE OF ANY ACTUAL OR INTENDED PUBLICATION OF THE 
SOURCE CODE. THE RECEIPT OR POSSESSION OF  THIS SOURCE CODE AND/OR RELATED 
INFORMATION DOES NOT CONVEY OR IMPLY ANY RIGHTS  TO REPRODUCE, DISCLOSE OR 
DISTRIBUTE ITS CONTENTS, OR TO MANUFACTURE, USE, OR SELL A PRODUCT THAT IT  MAY 
DESCRIBE.
@par
THE SIGMA PROGRAM AND ANY RELATED DOCUMENTATION OR TOOLS IS PROVIDED TO COMPANY 
"AS IS" AND "WITH ALL FAULTS", WITHOUT WARRANTY OF ANY KIND FROM SIGMA. COMPANY 
ASSUMES ALL RISKS THAT LICENSED MATERIALS ARE SUITABLE OR ACCURATE FOR 
COMPANY’S NEEDS AND COMPANY’S USE OF THE SIGMA PROGRAM IS AT COMPANY’S 
OWN DISCRETION AND RISK. SIGMA DOES NOT GUARANTEE THAT THE USE OF THE SIGMA 
PROGRAM IN A THIRD PARTY SERVICE ENVIRONMENT OR CLOUD SERVICES ENVIRONMENT WILL 
BE: (A) PERFORMED ERROR-FREE OR UNINTERRUPTED; (B) THAT SIGMA WILL CORRECT ANY 
THIRD PARTY SERVICE ENVIRONMENT OR CLOUD SERVICE ENVIRONMENT ERRORS; (C) THE 
THIRD PARTY SERVICE ENVIRONMENT OR CLOUD SERVICE ENVIRONMENT WILL OPERATE IN 
COMBINATION WITH COMPANY’S CONTENT OR COMPANY APPLICATIONS THAT UTILIZE THE 
SIGMA PROGRAM; (D) OR WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEMS, SERVICES OR 
DATA NOT PROVIDED BY SIGMA. COMPANY ACKNOWLEDGES THAT SIGMA DOES NOT CONTROL 
THE TRANSFER OF DATA OVER COMMUNICATIONS FACILITIES, INCLUDING THE INTERNET, 
AND THAT THE SERVICES MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS 
INHERENT IN THE USE OF SUCH COMMUNICATIONS FACILITIES. SIGMA IS NOT RESPONSIBLE 
FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH ISSUES. 
SIGMA IS NOT RESPONSIBLE FOR ANY ISSUES RELATED TO THE PERFORMANCE, OPERATION 
OR SECURITY OF THE THIRD PARTY SERVICE ENVIRONMENT OR CLOUD SERVICES 
ENVIRONMENT THAT ARISE FROM COMPANY CONTENT, COMPANY APPLICATIONS OR THIRD 
PARTY CONTENT. SIGMA DOES NOT MAKE ANY REPRESENTATION OR WARRANTY REGARDING THE 
RELIABILITY, ACCURACY, COMPLETENESS, CORRECTNESS, OR USEFULNESS OF THIRD PARTY 
CONTENT OR SERVICE OR THE SIGMA PROGRAM, AND DISCLAIMS ALL LIABILITIES ARISING 
FROM OR RELATED TO THE SIGMA PROGRAM OR THIRD PARTY CONTENT OR SERVICES. TO THE 
EXTENT NOT PROHIBITED BY LAW, THESE WARRANTIES ARE EXCLUSIVE. SIGMA OFFERS NO 
WARRANTY OF NON-INFRINGEMENT, TITLE, OR QUIET ENJOYMENT. NEITHER SIGMA NOR ITS 
SUPPLIERS OR LICENSORS SHALL BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR 
CONSEQUENTIAL DAMAGES OR LOSS (INCLUDING DAMAGES FOR LOSS OF BUSINESS, LOSS OF 
PROFITS, OR THE LIKE), ARISING OUT OF THIS AGREEMENT WHETHER BASED ON BREACH OF 
CONTRACT, INTELLECTUAL PROPERTY INFRINGEMENT, TORT (INCLUDING NEGLIGENCE), 
STRICT LIABILITY, PRODUCT LIABILITY OR OTHERWISE, EVEN IF SIGMA OR ITS 
REPRESENTATIVES HAVE BEEN ADVISED OF OR OTHERWISE SHOULD KNOW ABOUT THE 
POSSIBILITY OF SUCH DAMAGES. THERE ARE NO OTHER EXPRESS OR IMPLIED WARRANTIES 
OR CONDITIONS INCLUDING FOR SOFTWARE, HARDWARE, SYSTEMS, NETWORKS OR 
ENVIRONMENTS OR FOR MERCHANTABILITY, NONINFRINGEMENT, SATISFACTORY QUALITY AND 
FITNESS FOR A PARTICULAR PURPOSE.
@par
The Sigma Program  is not fault-tolerant and is not designed, manufactured or 
intended for use or resale as on-line control equipment in hazardous 
environments requiring fail-safe performance, such as in the operation of 
nuclear facilities, aircraft navigation or communication systems, air traffic 
control, direct life support machines, or weapons systems, in which the failure 
of the Sigma Program, or Company Applications created using the Sigma Program, 
could lead directly to death, personal injury, or severe physical or 
environmental damage ("High Risk Activities").  Sigma and its suppliers 
specifically disclaim any express or implied warranty of fitness for High Risk 
Activities.Without limiting Sigma’s obligation of confidentiality as further 
described in the Z-Wave Controller Development Kit Limited License Agreement, 
Sigma has no obligation to establish and maintain a data privacy and 
information security program with regard to Company’s use of any Third Party 
Service Environment or Cloud Service Environment. For the avoidance of doubt, 
Sigma shall not be responsible for physical, technical, security, 
administrative, and/or organizational safeguards that are designed to ensure 
the security and confidentiality of the Company Content or Company Application 
in any Third Party Service Environment or Cloud Service Environment that 
Company chooses to utilize.
*/
/**
 * @file    zwp_hcapi_zwave.c
 *
 * @brief   Z-Wave constants
 * @details Z-Wave constants - command class.
 *
 * @note    This file can be auto generated from Z-Wave specification XML file
 *
 * @author  Kumara
 *
 * @version 1.0 - 2013-09-12
 * - Initial version
 */

#include <stdio.h>

#include "zwp_hcapi.h"

/**
 * @brief Class to represent Command ID - Command Name mapping
 */
typedef struct
{
	uint8_t command_id;                      /**< Command ID */
	char *command_name;                      /**< Command Name */
} zwp_hcapi_zwave_command_t;

/**
 * @brief Class to represent Command Class ID - Command Class Name - Commands mapping
 */
typedef struct
{
	uint16_t class_id;                       /**< Command Class ID */
	char *class_name;                        /**< Command Class Name */
	zwp_hcapi_zwave_command_t command[256];  /**< Commands */
} zwp_hcapi_zwave_command_class_t;

/** Mappings between Command Class ID - Command Class Name - Command ID - Command Name */
zwp_hcapi_zwave_command_class_t g_zwp_hcapi_zwave_command_class[] = {
	{COMMAND_CLASS_ALARM, "COMMAND_CLASS_ALARM", {
		{EVENT_SUPPORTED_GET_V3, "EVENT_SUPPORTED_GET"},
		{EVENT_SUPPORTED_REPORT_V3, "EVENT_SUPPORTED_REPORT"},
		{EVENT_SUPPORTED_REPORT_V3, "EVENT_SUPPORTED_REPORT"},
		{ALARM_GET, "ALARM_GET"},
		{ALARM_REPORT, "ALARM_REPORT"},
		{ALARM_SET_V2, "ALARM_SET"},
		{ALARM_TYPE_SUPPORTED_GET_V2, "ALARM_TYPE_SUPPORTED_GET"},
		{ALARM_TYPE_SUPPORTED_REPORT_V2, "ALARM_TYPE_SUPPORTED_REPORT"}
	}},
	{COMMAND_CLASS_APPLICATION_STATUS, "COMMAND_CLASS_APPLICATION_STATUS", {
		{APPLICATION_BUSY, "APPLICATION_BUSY"},
		{APPLICATION_REJECTED_REQUEST, "APPLICATION_REJECTED_REQUEST"}
	}},
	{COMMAND_CLASS_ASSOCIATION_COMMAND_CONFIGURATION, "COMMAND_CLASS_ASSOCIATION_COMMAND_CONFIGURATION", {
		{COMMAND_RECORDS_SUPPORTED_GET, "COMMAND_RECORDS_SUPPORTED_GET"},
		{COMMAND_RECORDS_SUPPORTED_REPORT, "COMMAND_RECORDS_SUPPORTED_REPORT"},
		{COMMAND_CONFIGURATION_SET, "COMMAND_CONFIGURATION_SET"},
		{COMMAND_CONFIGURATION_GET, "COMMAND_CONFIGURATION_GET"},
		{COMMAND_CONFIGURATION_REPORT, "COMMAND_CONFIGURATION_REPORT"}
	}},
	{COMMAND_CLASS_ASSOCIATION, "COMMAND_CLASS_ASSOCIATION", {
		{ASSOCIATION_SET, "ASSOCIATION_SET"},
		{ASSOCIATION_GET, "ASSOCIATION_GET"},
		{ASSOCIATION_REPORT, "ASSOCIATION_REPORT"},
		{ASSOCIATION_REMOVE, "ASSOCIATION_REMOVE"},
		{ASSOCIATION_GROUPINGS_GET, "ASSOCIATION_GROUPINGS_GET"},
		{ASSOCIATION_GROUPINGS_REPORT, "ASSOCIATION_GROUPINGS_REPORT"}
	}},
	{COMMAND_CLASS_AV_CONTENT_DIRECTORY_MD, "COMMAND_CLASS_AV_CONTENT_DIRECTORY_MD", {
		{AV_CONTENT_BROWSE_MD_GET, "AV_CONTENT_BROWSE_MD_GET"},
		{AV_CONTENT_BROWSE_MD_REPORT, "AV_CONTENT_BROWSE_MD_REPORT"},
		{AV_CONTENT_BROWSE_MD_BY_LETTER_GET, "AV_CONTENT_BROWSE_MD_BY_LETTER_GET"},
		{AV_CONTENT_BROWSE_MD_BY_LETTER_REPORT, "AV_CONTENT_BROWSE_MD_BY_LETTER_REPORT"},
		{AV_CONTENT_BROWSE_MD_CHILD_COUNT_GET, "AV_CONTENT_BROWSE_MD_CHILD_COUNT_GET"},
		{AV_CONTENT_BROWSE_MD_CHILD_COUNT_REPORT, "AV_CONTENT_BROWSE_MD_CHILD_COUNT_REPORT"},
		{AV_MATCH_ITEM_TO_RENDERER_MD_GET, "AV_MATCH_ITEM_TO_RENDERER_MD_GET"},
		{AV_MATCH_ITEM_TO_RENDERER_MD_REPORT, "AV_MATCH_ITEM_TO_RENDERER_MD_REPORT"}
	}},
	{COMMAND_CLASS_AV_CONTENT_SEARCH_MD, "COMMAND_CLASS_AV_CONTENT_SEARCH_MD", {
		{AV_CONTENT_SEARCH_MD_GET, "AV_CONTENT_SEARCH_MD_GET"},
		{AV_CONTENT_SEARCH_MD_REPORT, "AV_CONTENT_SEARCH_MD_REPORT"}
	}},
	{COMMAND_CLASS_AV_RENDERER_STATUS, "COMMAND_CLASS_AV_RENDERER_STATUS", {
		{AV_RENDERER_STATUS_GET, "AV_RENDERER_STATUS_GET"},
		{AV_RENDERER_STATUS_REPORT, "AV_RENDERER_STATUS_REPORT"}
	}},
	{COMMAND_CLASS_AV_TAGGING_MD, "COMMAND_CLASS_AV_TAGGING_MD", {
		{AV_TAGGING_MD_GET, "AV_TAGGING_MD_GET"},
		{AV_TAGGING_MD_REPORT, "AV_TAGGING_MD_REPORT"}
	}},
	{COMMAND_CLASS_BASIC_TARIFF_INFO, "COMMAND_CLASS_BASIC_TARIFF_INFO", {
		{BASIC_TARIFF_INFO_GET, "BASIC_TARIFF_INFO_GET"},
		{BASIC_TARIFF_INFO_REPORT, "BASIC_TARIFF_INFO_REPORT"}
	}},
	{COMMAND_CLASS_BASIC_WINDOW_COVERING, "COMMAND_CLASS_BASIC_WINDOW_COVERING", {
		{BASIC_WINDOW_COVERING_START_LEVEL_CHANGE, "BASIC_WINDOW_COVERING_START_LEVEL_CHANGE"},
		{BASIC_WINDOW_COVERING_STOP_LEVEL_CHANGE, "BASIC_WINDOW_COVERING_STOP_LEVEL_CHANGE"}
	}},
	{COMMAND_CLASS_BASIC, "COMMAND_CLASS_BASIC", {
		{BASIC_SET, "BASIC_SET"},
		{BASIC_GET, "BASIC_GET"},
		{BASIC_REPORT, "BASIC_REPORT"}
	}},
	{COMMAND_CLASS_BATTERY, "COMMAND_CLASS_BATTERY", {
		{BATTERY_GET, "BATTERY_GET"},
		{BATTERY_REPORT, "BATTERY_REPORT"}
	}},
	{COMMAND_CLASS_CENTRAL_SCENE, "COMMAND_CLASS_CENTRAL_SCENE", {
		{ CENTRAL_SCENE_NOTIFICATION, "CENTRAL_SCENE_NOTIFICATION" },
		{ CENTRAL_SCENE_SUPPORTED_GET, "CENTRAL_SCENE_SUPPORTED_GET" },
		{ CENTRAL_SCENE_SUPPORTED_REPORT, "CENTRAL_SCENE_SUPPORTED_REPORT" }
	} },
	{COMMAND_CLASS_CHIMNEY_FAN, "COMMAND_CLASS_CHIMNEY_FAN", {
		{CHIMNEY_FAN_STATE_SET, "CHIMNEY_FAN_STATE_SET"},
		{CHIMNEY_FAN_STATE_GET, "CHIMNEY_FAN_STATE_GET"},
		{CHIMNEY_FAN_STATE_REPORT, "CHIMNEY_FAN_STATE_REPORT"},
		{CHIMNEY_FAN_SPEED_SET, "CHIMNEY_FAN_SPEED_SET"},
		{CHIMNEY_FAN_SPEED_GET, "CHIMNEY_FAN_SPEED_GET"},
		{CHIMNEY_FAN_SPEED_REPORT, "CHIMNEY_FAN_SPEED_REPORT"},
		{CHIMNEY_FAN_START_TEMP_SET, "CHIMNEY_FAN_START_TEMP_SET"},
		{CHIMNEY_FAN_START_TEMP_GET, "CHIMNEY_FAN_START_TEMP_GET"},
		{CHIMNEY_FAN_START_TEMP_REPORT, "CHIMNEY_FAN_START_TEMP_REPORT"},
		{CHIMNEY_FAN_STOP_TEMP_SET, "CHIMNEY_FAN_STOP_TEMP_SET"},
		{CHIMNEY_FAN_STOP_TEMP_GET, "CHIMNEY_FAN_STOP_TEMP_GET"},
		{CHIMNEY_FAN_STOP_TEMP_REPORT, "CHIMNEY_FAN_STOP_TEMP_REPORT"},
		{CHIMNEY_FAN_ALARM_TEMP_SET, "CHIMNEY_FAN_ALARM_TEMP_SET"},
		{CHIMNEY_FAN_ALARM_TEMP_GET, "CHIMNEY_FAN_ALARM_TEMP_GET"},
		{CHIMNEY_FAN_ALARM_TEMP_REPORT, "CHIMNEY_FAN_ALARM_TEMP_REPORT"},
		{CHIMNEY_FAN_BOOST_TIME_SET, "CHIMNEY_FAN_BOOST_TIME_SET"},
		{CHIMNEY_FAN_BOOST_TIME_GET, "CHIMNEY_FAN_BOOST_TIME_GET"},
		{CHIMNEY_FAN_BOOST_TIME_REPORT, "CHIMNEY_FAN_BOOST_TIME_REPORT"},
		{CHIMNEY_FAN_STOP_TIME_SET, "CHIMNEY_FAN_STOP_TIME_SET"},
		{CHIMNEY_FAN_STOP_TIME_GET, "CHIMNEY_FAN_STOP_TIME_GET"},
		{CHIMNEY_FAN_STOP_TIME_REPORT, "CHIMNEY_FAN_STOP_TIME_REPORT"},
		{CHIMNEY_FAN_MODE_SET, "CHIMNEY_FAN_MODE_SET"},
		{CHIMNEY_FAN_MODE_GET, "CHIMNEY_FAN_MODE_GET"},
		{CHIMNEY_FAN_MODE_REPORT, "CHIMNEY_FAN_MODE_REPORT"},
		{CHIMNEY_FAN_SETUP_SET, "CHIMNEY_FAN_SETUP_SET"},
		{CHIMNEY_FAN_SETUP_GET, "CHIMNEY_FAN_SETUP_GET"},
		{CHIMNEY_FAN_SETUP_REPORT, "CHIMNEY_FAN_SETUP_REPORT"},
		{CHIMNEY_FAN_STATUS_GET, "CHIMNEY_FAN_STATUS_GET"},
		{CHIMNEY_FAN_STATUS_REPORT, "CHIMNEY_FAN_STATUS_REPORT"},
		{CHIMNEY_FAN_ALARM_LOG_SET, "CHIMNEY_FAN_ALARM_LOG_SET"},
		{CHIMNEY_FAN_ALARM_LOG_GET, "CHIMNEY_FAN_ALARM_LOG_GET"},
		{CHIMNEY_FAN_ALARM_LOG_REPORT, "CHIMNEY_FAN_ALARM_LOG_REPORT"},
		{CHIMNEY_FAN_ALARM_STATUS_SET, "CHIMNEY_FAN_ALARM_STATUS_SET"},
		{CHIMNEY_FAN_ALARM_STATUS_GET, "CHIMNEY_FAN_ALARM_STATUS_GET"},
		{CHIMNEY_FAN_ALARM_STATUS_REPORT, "CHIMNEY_FAN_ALARM_STATUS_REPORT"},
		{CHIMNEY_FAN_MIN_SPEED_SET, "CHIMNEY_FAN_MIN_SPEED_SET"},
		{CHIMNEY_FAN_MIN_SPEED_GET, "CHIMNEY_FAN_MIN_SPEED_GET"},
		{CHIMNEY_FAN_MIN_SPEED_REPORT, "CHIMNEY_FAN_MIN_SPEED_REPORT"},
		{CHIMNEY_FAN_DEFAULT_SET, "CHIMNEY_FAN_DEFAULT_SET"}
	}},
	{COMMAND_CLASS_CLIMATE_CONTROL_SCHEDULE, "COMMAND_CLASS_CLIMATE_CONTROL_SCHEDULE", {
		{SCHEDULE_SET, "SCHEDULE_SET"},
		{SCHEDULE_GET, "SCHEDULE_GET"},
		{SCHEDULE_REPORT, "SCHEDULE_REPORT"},
		{SCHEDULE_CHANGED_GET, "SCHEDULE_CHANGED_GET"},
		{SCHEDULE_CHANGED_REPORT, "SCHEDULE_CHANGED_REPORT"},
		{SCHEDULE_OVERRIDE_SET, "SCHEDULE_OVERRIDE_SET"},
		{SCHEDULE_OVERRIDE_GET, "SCHEDULE_OVERRIDE_GET"},
		{SCHEDULE_OVERRIDE_REPORT, "SCHEDULE_OVERRIDE_REPORT"}
	}},
	{COMMAND_CLASS_CLOCK, "COMMAND_CLASS_CLOCK", {
		{CLOCK_SET, "CLOCK_SET"},
		{CLOCK_GET, "CLOCK_GET"},
		{CLOCK_REPORT, "CLOCK_REPORT"}
	}},
	{COMMAND_CLASS_CONFIGURATION, "COMMAND_CLASS_CONFIGURATION", {
		{CONFIGURATION_SET, "CONFIGURATION_SET"},
		{CONFIGURATION_GET, "CONFIGURATION_GET"},
		{CONFIGURATION_REPORT, "CONFIGURATION_REPORT"},
		{CONFIGURATION_BULK_SET_V2, "CONFIGURATION_BULK_SET"},
		{CONFIGURATION_BULK_GET_V2, "CONFIGURATION_BULK_GET"},
		{CONFIGURATION_BULK_REPORT_V2, "CONFIGURATION_BULK_REPORT"}
	}},
	{COMMAND_CLASS_CONTROLLER_REPLICATION, "COMMAND_CLASS_CONTROLLER_REPLICATION", {
		{CTRL_REPLICATION_TRANSFER_GROUP, "CTRL_REPLICATION_TRANSFER_GROUP"},
		{CTRL_REPLICATION_TRANSFER_GROUP_NAME, "CTRL_REPLICATION_TRANSFER_GROUP_NAME"},
		{CTRL_REPLICATION_TRANSFER_SCENE, "CTRL_REPLICATION_TRANSFER_SCENE"},
		{CTRL_REPLICATION_TRANSFER_SCENE_NAME, "CTRL_REPLICATION_TRANSFER_SCENE_NAME"}
	}},
	{COMMAND_CLASS_CRC_16_ENCAP, "COMMAND_CLASS_CRC_16_ENCAP", {
		{CRC_16_ENCAP, "CRC_16_ENCAP"}
	}},
	{COMMAND_CLASS_DCP_CONFIG, "COMMAND_CLASS_DCP_CONFIG", {
		{DCP_LIST_REMOVE, "DCP_LIST_REMOVE"},
		{DCP_LIST_SET, "DCP_LIST_SET"},
		{DCP_LIST_SUPPORTED_GET, "DCP_LIST_SUPPORTED_GET"},
		{DCP_LIST_SUPPORTED_REPORT, "DCP_LIST_SUPPORTED_REPORT"}
	}},
	{COMMAND_CLASS_DCP_MONITOR, "COMMAND_CLASS_DCP_MONITOR", {
		{DCP_EVENT_STATUS_GET, "DCP_EVENT_STATUS_GET"},
		{DCP_EVENT_STATUS_REPORT, "DCP_EVENT_STATUS_REPORT"},
		{DCP_LIST_GET, "DCP_LIST_GET"},
		{DCP_LIST_REPORT, "DCP_LIST_REPORT"}
	}},
	{COMMAND_CLASS_DOOR_LOCK_LOGGING, "COMMAND_CLASS_DOOR_LOCK_LOGGING", {
		{DOOR_LOCK_LOGGING_RECORDS_SUPPORTED_GET, "DOOR_LOCK_LOGGING_RECORDS_SUPPORTED_GET"},
		{DOOR_LOCK_LOGGING_RECORDS_SUPPORTED_REPORT, "DOOR_LOCK_LOGGING_RECORDS_SUPPORTED_REPORT"},
		{RECORD_GET, "RECORD_GET"},
		{RECORD_REPORT, "RECORD_REPORT"}
	}},
	{COMMAND_CLASS_DOOR_LOCK, "COMMAND_CLASS_DOOR_LOCK", {
		{DOOR_LOCK_CONFIGURATION_GET, "DOOR_LOCK_CONFIGURATION_GET"},
		{DOOR_LOCK_CONFIGURATION_REPORT, "DOOR_LOCK_CONFIGURATION_REPORT"},
		{DOOR_LOCK_CONFIGURATION_SET, "DOOR_LOCK_CONFIGURATION_SET"},
		{DOOR_LOCK_OPERATION_GET, "DOOR_LOCK_OPERATION_GET"},
		{DOOR_LOCK_OPERATION_REPORT, "DOOR_LOCK_OPERATION_REPORT"},
		{DOOR_LOCK_OPERATION_SET, "DOOR_LOCK_OPERATION_SET"}
	}},
	{COMMAND_CLASS_ENERGY_PRODUCTION, "COMMAND_CLASS_ENERGY_PRODUCTION", {
		{ENERGY_PRODUCTION_GET, "ENERGY_PRODUCTION_GET"},
		{ENERGY_PRODUCTION_REPORT, "ENERGY_PRODUCTION_REPORT"}
	}},
	{COMMAND_CLASS_FIRMWARE_UPDATE_MD, "COMMAND_CLASS_FIRMWARE_UPDATE_MD", {
		{FIRMWARE_MD_GET, "FIRMWARE_MD_GET"},
		{FIRMWARE_MD_REPORT, "FIRMWARE_MD_REPORT"},
		{FIRMWARE_UPDATE_MD_GET, "FIRMWARE_UPDATE_MD_GET"},
		{FIRMWARE_UPDATE_MD_REPORT, "FIRMWARE_UPDATE_MD_REPORT"},
		{FIRMWARE_UPDATE_MD_REQUEST_GET, "FIRMWARE_UPDATE_MD_REQUEST_GET"},
		{FIRMWARE_UPDATE_MD_REQUEST_REPORT, "FIRMWARE_UPDATE_MD_REQUEST_REPORT"},
		{FIRMWARE_UPDATE_MD_STATUS_REPORT, "FIRMWARE_UPDATE_MD_STATUS_REPORT"}
	}},
	{COMMAND_CLASS_GEOGRAPHIC_LOCATION, "COMMAND_CLASS_GEOGRAPHIC_LOCATION", {
		{GEOGRAPHIC_LOCATION_GET, "GEOGRAPHIC_LOCATION_GET"},
		{GEOGRAPHIC_LOCATION_REPORT, "GEOGRAPHIC_LOCATION_REPORT"},
		{GEOGRAPHIC_LOCATION_SET, "GEOGRAPHIC_LOCATION_SET"}
	}},
	{COMMAND_CLASS_GROUPING_NAME, "COMMAND_CLASS_GROUPING_NAME", {
		{GROUPING_NAME_GET, "GROUPING_NAME_GET"},
		{GROUPING_NAME_REPORT, "GROUPING_NAME_REPORT"},
		{GROUPING_NAME_SET, "GROUPING_NAME_SET"}
	}},
	{COMMAND_CLASS_HAIL, "COMMAND_CLASS_HAIL", {
		{HAIL, "HAIL"}
	}},
	{COMMAND_CLASS_HRV_CONTROL, "COMMAND_CLASS_HRV_CONTROL", {
		{HRV_CONTROL_BYPASS_GET, "HRV_CONTROL_BYPASS_GET"},
		{HRV_CONTROL_BYPASS_REPORT, "HRV_CONTROL_BYPASS_REPORT"},
		{HRV_CONTROL_BYPASS_SET, "HRV_CONTROL_BYPASS_SET"},
		{HRV_CONTROL_MODE_GET, "HRV_CONTROL_MODE_GET"},
		{HRV_CONTROL_MODE_REPORT, "HRV_CONTROL_MODE_REPORT"},
		{HRV_CONTROL_MODE_SET, "HRV_CONTROL_MODE_SET"},
		{HRV_CONTROL_MODE_SUPPORTED_GET, "HRV_CONTROL_MODE_SUPPORTED_GET"},
		{HRV_CONTROL_MODE_SUPPORTED_REPORT, "HRV_CONTROL_MODE_SUPPORTED_REPORT"},
		{HRV_CONTROL_VENTILATION_RATE_GET, "HRV_CONTROL_VENTILATION_RATE_GET"},
		{HRV_CONTROL_VENTILATION_RATE_REPORT, "HRV_CONTROL_VENTILATION_RATE_REPORT"},
		{HRV_CONTROL_VENTILATION_RATE_SET, "HRV_CONTROL_VENTILATION_RATE_SET"}
	}},
	{COMMAND_CLASS_HRV_STATUS, "COMMAND_CLASS_HRV_STATUS", {
		{HRV_STATUS_GET, "HRV_STATUS_GET"},
		{HRV_STATUS_REPORT, "HRV_STATUS_REPORT"},
		{HRV_STATUS_SUPPORTED_GET, "HRV_STATUS_SUPPORTED_GET"},
		{HRV_STATUS_SUPPORTED_REPORT, "HRV_STATUS_SUPPORTED_REPORT"}
	}},
	{COMMAND_CLASS_INDICATOR, "COMMAND_CLASS_INDICATOR", {
		{INDICATOR_GET, "INDICATOR_GET"},
		{INDICATOR_REPORT, "INDICATOR_REPORT"},
		{INDICATOR_SET, "INDICATOR_SET"}
	}},
	{COMMAND_CLASS_IP_CONFIGURATION, "COMMAND_CLASS_IP_CONFIGURATION", {
		{IP_CONFIGURATION_GET, "IP_CONFIGURATION_GET"},
		{IP_CONFIGURATION_RELEASE, "IP_CONFIGURATION_RELEASE"},
		{IP_CONFIGURATION_RENEW, "IP_CONFIGURATION_RENEW"},
		{IP_CONFIGURATION_REPORT, "IP_CONFIGURATION_REPORT"},
		{IP_CONFIGURATION_SET, "IP_CONFIGURATION_SET"}
	}},
	{COMMAND_CLASS_LANGUAGE, "COMMAND_CLASS_LANGUAGE", {
		{LANGUAGE_GET, "LANGUAGE_GET"},
		{LANGUAGE_REPORT, "LANGUAGE_REPORT"},
		{LANGUAGE_SET, "LANGUAGE_SET"}
	}},
	{COMMAND_CLASS_LOCK, "COMMAND_CLASS_LOCK", {
		{LOCK_GET, "LOCK_GET"},
		{LOCK_REPORT, "LOCK_REPORT"},
		{LOCK_SET, "LOCK_SET"}
	}},
	{COMMAND_CLASS_MANUFACTURER_PROPRIETARY, "COMMAND_CLASS_MANUFACTURER_PROPRIETARY"},
	{COMMAND_CLASS_MANUFACTURER_SPECIFIC, "COMMAND_CLASS_MANUFACTURER_SPECIFIC", {
		{MANUFACTURER_SPECIFIC_GET, "MANUFACTURER_SPECIFIC_GET"},
		{MANUFACTURER_SPECIFIC_REPORT, "MANUFACTURER_SPECIFIC_REPORT"},
		{DEVICE_SPECIFIC_GET_V2, "DEVICE_SPECIFIC_GET"},
		{DEVICE_SPECIFIC_REPORT_V2, "DEVICE_SPECIFIC_REPORT"}
	}},
	{COMMAND_CLASS_MARK, "COMMAND_CLASS_MARK"},
	{COMMAND_CLASS_METER_PULSE, "COMMAND_CLASS_METER_PULSE", {
		{METER_PULSE_GET, "METER_PULSE_GET"},
		{METER_PULSE_REPORT, "METER_PULSE_REPORT"}
	}},
	{COMMAND_CLASS_METER_TBL_CONFIG, "COMMAND_CLASS_METER_TBL_CONFIG", {
		{METER_TBL_TABLE_POINT_ADM_NO_SET, "METER_TBL_TABLE_POINT_ADM_NO_SET"}
	}},
	{COMMAND_CLASS_METER_TBL_MONITOR, "COMMAND_CLASS_METER_TBL_MONITOR", {
		{METER_TBL_STATUS_REPORT, "METER_TBL_STATUS_REPORT"},
		{METER_TBL_STATUS_DATE_GET, "METER_TBL_STATUS_DATE_GET"},
		{METER_TBL_STATUS_DEPTH_GET, "METER_TBL_STATUS_DEPTH_GET"},
		{METER_TBL_STATUS_SUPPORTED_GET, "METER_TBL_STATUS_SUPPORTED_GET"},
		{METER_TBL_STATUS_SUPPORTED_REPORT, "METER_TBL_STATUS_SUPPORTED_REPORT"},
		{METER_TBL_CURRENT_DATA_GET, "METER_TBL_CURRENT_DATA_GET"},
		{METER_TBL_CURRENT_DATA_REPORT, "METER_TBL_CURRENT_DATA_REPORT"},
		{METER_TBL_HISTORICAL_DATA_GET, "METER_TBL_HISTORICAL_DATA_GET"},
		{METER_TBL_HISTORICAL_DATA_REPORT, "METER_TBL_HISTORICAL_DATA_REPORT"},
		{METER_TBL_REPORT, "METER_TBL_REPORT"},
		{METER_TBL_TABLE_CAPABILITY_GET, "METER_TBL_TABLE_CAPABILITY_GET"},
		{METER_TBL_TABLE_ID_GET, "METER_TBL_TABLE_ID_GET"},
		{METER_TBL_TABLE_ID_REPORT, "METER_TBL_TABLE_ID_REPORT"},
		{METER_TBL_TABLE_POINT_ADM_NO_GET, "METER_TBL_TABLE_POINT_ADM_NO_GET"},
		{METER_TBL_TABLE_POINT_ADM_NO_REPORT, "METER_TBL_TABLE_POINT_ADM_NO_REPORT"}
	}},
	{COMMAND_CLASS_METER_TBL_PUSH, "COMMAND_CLASS_METER_TBL_PUSH", {
		{METER_TBL_PUSH_CONFIGURATION_GET, "METER_TBL_PUSH_CONFIGURATION_GET"},
		{METER_TBL_PUSH_CONFIGURATION_REPORT, "METER_TBL_PUSH_CONFIGURATION_REPORT"},
		{METER_TBL_PUSH_CONFIGURATION_SET, "METER_TBL_PUSH_CONFIGURATION_SET"}
	}},
	{COMMAND_CLASS_METER, "COMMAND_CLASS_METER", {
		{METER_GET, "METER_GET"},
		{METER_REPORT, "METER_REPORT"}
	}},
	{COMMAND_CLASS_MTP_WINDOW_COVERING, "COMMAND_CLASS_MTP_WINDOW_COVERING", {
		{MOVE_TO_POSITION_GET, "MOVE_TO_POSITION_GET"},
		{MOVE_TO_POSITION_REPORT, "MOVE_TO_POSITION_REPORT"},
		{MOVE_TO_POSITION_SET, "MOVE_TO_POSITION_SET"}
		}},
	{COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION_V2, "COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION", {
		{MULTI_CHANNEL_ASSOCIATION_GET_V2, "MULTI_CHANNEL_ASSOCIATION_GET"},
		{MULTI_CHANNEL_ASSOCIATION_GROUPINGS_GET_V2, "MULTI_CHANNEL_ASSOCIATION_GROUPINGS_GET"},
		{MULTI_CHANNEL_ASSOCIATION_GROUPINGS_REPORT_V2, "MULTI_CHANNEL_ASSOCIATION_GROUPINGS_REPORT"},
		{MULTI_CHANNEL_ASSOCIATION_REMOVE_V2, "MULTI_CHANNEL_ASSOCIATION_REMOVE"},
		{MULTI_CHANNEL_ASSOCIATION_REPORT_V2, "MULTI_CHANNEL_ASSOCIATION_REPORT"},
		{MULTI_CHANNEL_ASSOCIATION_SET_V2, "MULTI_CHANNEL_ASSOCIATION_SET"}
		}},
	{COMMAND_CLASS_MULTI_CHANNEL_V2, "COMMAND_CLASS_MULTI_CHANNEL", {
		{MULTI_CHANNEL_CAPABILITY_GET_V2, "MULTI_CHANNEL_CAPABILITY_GET"},
		{MULTI_CHANNEL_CAPABILITY_REPORT_V2, "MULTI_CHANNEL_CAPABILITY_REPORT"},
		{MULTI_CHANNEL_CMD_ENCAP_V2, "MULTI_CHANNEL_CMD_ENCAP"},
		{MULTI_CHANNEL_END_POINT_FIND_V2, "MULTI_CHANNEL_END_POINT_FIND"},
		{MULTI_CHANNEL_END_POINT_FIND_REPORT_V2, "MULTI_CHANNEL_END_POINT_FIND_REPORT"},
		{MULTI_CHANNEL_END_POINT_GET_V2, "MULTI_CHANNEL_END_POINT_GET"},
		{MULTI_CHANNEL_END_POINT_REPORT_V2, "MULTI_CHANNEL_END_POINT_REPORT"},
		{MULTI_INSTANCE_CMD_ENCAP, "MULTI_INSTANCE_CMD_ENCAP"},
		{MULTI_INSTANCE_GET, "MULTI_INSTANCE_GET"},
		{MULTI_INSTANCE_REPORT, "MULTI_INSTANCE_REPORT"}
		}},
	{COMMAND_CLASS_MULTI_CMD, "COMMAND_CLASS_MULTI_CMD", {
		{MULTI_CMD_ENCAP, "MULTI_CMD_ENCAP"}
		}},
	{COMMAND_CLASS_NETWORK_MANAGEMENT_PROXY, "COMMAND_CLASS_NETWORK_MANAGEMENT_PROXY", {
		{NODE_INFO_CACHED_GET, "NODE_INFO_CACHED_GET"},
		{NODE_INFO_CACHED_REPORT, "NODE_INFO_CACHED_REPORT"},
		{NODE_LIST_GET, "NODE_LIST_GET"},
		{NODE_LIST_REPORT, "NODE_LIST_REPORT"}
		}},
	{COMMAND_CLASS_NETWORK_MANAGEMENT_BASIC, "COMMAND_CLASS_NETWORK_MANAGEMENT_BASIC", {
		{LEARN_MODE_SET, "LEARN_MODE_SET"},
		{LEARN_MODE_SET_STATUS, "LEARN_MODE_SET_STATUS"},
		{NODE_INFORMATION_SEND, "NODE_INFORMATION_SEND"},
		{NETWORK_UPDATE_REQUEST, "NETWORK_UPDATE_REQUEST"},
		{NETWORK_UPDATE_REQUEST_STATUS, "NETWORK_UPDATE_REQUEST_STATUS"},
		{DEFAULT_SET, "DEFAULT_SET"},
		{DEFAULT_SET_COMPLETE, "DEFAULT_SET_COMPLETE"}
		}},
	{COMMAND_CLASS_NETWORK_MANAGEMENT_INCLUSION, "COMMAND_CLASS_NETWORK_MANAGEMENT_INCLUSION", {
		{FAILED_NODE_REMOVE, "FAILED_NODE_REMOVE"},
		{FAILED_NODE_REMOVE_STATUS, "FAILED_NODE_REMOVE_STATUS"},
		{NODE_ADD, "NODE_ADD"},
		{NODE_ADD_STATUS, "NODE_ADD_STATUS"},
		{NODE_REMOVE, "NODE_REMOVE"},
		{NODE_REMOVE_STATUS, "NODE_REMOVE_STATUS"},
		{FAILED_NODE_REPLACE, "FAILED_NODE_REPLACE"},
		{FAILED_NODE_REPLACE_STATUS, "FAILED_NODE_REPLACE_STATUS"},
		{NODE_NEIGHBOR_UPDATE_REQUEST, "NODE_NEIGHBOR_UPDATE_REQUEST"},
		{NODE_NEIGHBOR_UPDATE_STATUS, "NODE_NEIGHBOR_UPDATE_STATUS"},
		{RETURN_ROUTE_ASSIGN, "RETURN_ROUTE_ASSIGN"},
		{RETURN_ROUTE_ASSIGN_COMPLETE, "RETURN_ROUTE_ASSIGN_COMPLETE"},
		{RETURN_ROUTE_DELETE, "RETURN_ROUTE_DELETE"},
		{RETURN_ROUTE_DELETE_COMPLETE, "RETURN_ROUTE_DELETE_COMPLETE"}
		}},
	{COMMAND_CLASS_NO_OPERATION, "COMMAND_CLASS_NO_OPERATION"},
	{COMMAND_CLASS_NODE_NAMING, "COMMAND_CLASS_NODE_NAMING", {
		{NODE_NAMING_NODE_LOCATION_REPORT, "NODE_NAMING_NODE_LOCATION_REPORT"},
		{NODE_NAMING_NODE_LOCATION_SET, "NODE_NAMING_NODE_LOCATION_SET"},
		{NODE_NAMING_NODE_LOCATION_GET, "NODE_NAMING_NODE_LOCATION_GET"},
		{NODE_NAMING_NODE_NAME_GET, "NODE_NAMING_NODE_NAME_GET"},
		{NODE_NAMING_NODE_NAME_REPORT, "NODE_NAMING_NODE_NAME_REPORT"},
		{NODE_NAMING_NODE_NAME_SET, "NODE_NAMING_NODE_NAME_SET"}
		}},
	{COMMAND_CLASS_NON_INTEROPERABLE, "COMMAND_CLASS_NON_INTEROPERABLE"},
	{COMMAND_CLASS_POWERLEVEL, "COMMAND_CLASS_POWERLEVEL", {
		{POWERLEVEL_GET, "POWERLEVEL_GET"},
		{POWERLEVEL_REPORT, "POWERLEVEL_REPORT"},
		{POWERLEVEL_SET, "POWERLEVEL_SET"},
		{POWERLEVEL_TEST_NODE_GET, "POWERLEVEL_TEST_NODE_GET"},
		{POWERLEVEL_TEST_NODE_REPORT, "POWERLEVEL_TEST_NODE_REPORT"},
		{POWERLEVEL_TEST_NODE_SET, "POWERLEVEL_TEST_NODE_SET"}
		}},
	{COMMAND_CLASS_PREPAYMENT_ENCAPSULATION, "COMMAND_CLASS_PREPAYMENT_ENCAPSULATION", {
		{CMD_ENCAPSULATION, "CMD_ENCAPSULATION"}
		}},
	{COMMAND_CLASS_PREPAYMENT, "COMMAND_CLASS_PREPAYMENT", {
		{PREPAYMENT_BALANCE_GET, "PREPAYMENT_BALANCE_GET"},
		{PREPAYMENT_BALANCE_REPORT, "PREPAYMENT_BALANCE_REPORT"},
		{PREPAYMENT_SUPPORTED_GET, "PREPAYMENT_SUPPORTED_GET"},
		{PREPAYMENT_SUPPORTED_REPORT, "PREPAYMENT_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_PROPRIETARY, "COMMAND_CLASS_PROPRIETARY", {
		{PROPRIETARY_GET, "PROPRIETARY_GET"},
		{PROPRIETARY_REPORT, "PROPRIETARY_REPORT"},
		{PROPRIETARY_SET, "PROPRIETARY_SET"}
		}},
	{COMMAND_CLASS_PROTECTION, "COMMAND_CLASS_PROTECTION", {
		{PROTECTION_GET, "PROTECTION_GET"},
		{PROTECTION_REPORT, "PROTECTION_REPORT"},
		{PROTECTION_SET, "PROTECTION_SET"},
		{PROTECTION_EC_GET_V2, "PROTECTION_EC_GET"},
		{PROTECTION_EC_REPORT_V2, "PROTECTION_EC_REPORT"},
		{PROTECTION_EC_SET_V2, "PROTECTION_EC_SET"},
		{PROTECTION_SUPPORTED_GET_V2, "PROTECTION_SUPPORTED_GET"},
		{PROTECTION_SUPPORTED_REPORT_V2, "PROTECTION_SUPPORTED_REPORT"},
		{PROTECTION_TIMEOUT_GET_V2, "PROTECTION_TIMEOUT_GET"},
		{PROTECTION_TIMEOUT_REPORT_V2, "PROTECTION_TIMEOUT_REPORT"},
		{PROTECTION_TIMEOUT_SET_V2, "PROTECTION_TIMEOUT_SET"}
		}},
	{COMMAND_CLASS_RATE_TBL_CONFIG, "COMMAND_CLASS_RATE_TBL_CONFIG", {
		{RATE_TBL_REMOVE, "RATE_TBL_REMOVE"},
		{RATE_TBL_SET, "RATE_TBL_SET"}
		}},
	{COMMAND_CLASS_RATE_TBL_MONITOR, "COMMAND_CLASS_RATE_TBL_MONITOR", {
		{RATE_TBL_ACTIVE_RATE_GET, "RATE_TBL_ACTIVE_RATE_GET"},
		{RATE_TBL_ACTIVE_RATE_REPORT, "RATE_TBL_ACTIVE_RATE_REPORT"},
		{RATE_TBL_CURRENT_DATA_GET, "RATE_TBL_CURRENT_DATA_GET"},
		{RATE_TBL_CURRENT_DATA_REPORT, "RATE_TBL_CURRENT_DATA_REPORT"},
		{RATE_TBL_GET, "RATE_TBL_GET"},
		{RATE_TBL_HISTORICAL_DATA_GET, "RATE_TBL_HISTORICAL_DATA_GET"},
		{RATE_TBL_HISTORICAL_DATA_REPORT, "RATE_TBL_HISTORICAL_DATA_REPORT"},
		{RATE_TBL_REPORT, "RATE_TBL_REPORT"},
		{RATE_TBL_SUPPORTED_GET, "RATE_TBL_SUPPORTED_GET"},
		{RATE_TBL_SUPPORTED_REPORT, "RATE_TBL_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_REMOTE_ASSOCIATION_ACTIVATE, "COMMAND_CLASS_REMOTE_ASSOCIATION_ACTIVATE", {
		{REMOTE_ASSOCIATION_ACTIVATE, "REMOTE_ASSOCIATION_ACTIVATE"}
		}},
	{COMMAND_CLASS_REMOTE_ASSOCIATION, "COMMAND_CLASS_REMOTE_ASSOCIATION", {
		{REMOTE_ASSOCIATION_CONFIGURATION_GET, "REMOTE_ASSOCIATION_CONFIGURATION_GET"},
		{REMOTE_ASSOCIATION_CONFIGURATION_REPORT, "REMOTE_ASSOCIATION_CONFIGURATION_REPORT"},
		{REMOTE_ASSOCIATION_CONFIGURATION_SET, "REMOTE_ASSOCIATION_CONFIGURATION_SET"}
		}},
	{COMMAND_CLASS_SCENE_ACTIVATION, "COMMAND_CLASS_SCENE_ACTIVATION", {
		{SCENE_ACTIVATION_SET, "SCENE_ACTIVATION_SET"}
		}},
	{COMMAND_CLASS_SCENE_ACTUATOR_CONF, "COMMAND_CLASS_SCENE_ACTUATOR_CONF", {
		{SCENE_ACTUATOR_CONF_GET, "SCENE_ACTUATOR_CONF_GET"},
		{SCENE_ACTUATOR_CONF_REPORT, "SCENE_ACTUATOR_CONF_REPORT"},
		{SCENE_ACTUATOR_CONF_SET, "SCENE_ACTUATOR_CONF_SET"}
		}},
	{COMMAND_CLASS_SCENE_CONTROLLER_CONF, "COMMAND_CLASS_SCENE_CONTROLLER_CONF", {
		{SCENE_CONTROLLER_CONF_GET, "SCENE_CONTROLLER_CONF_GET"},
		{SCENE_CONTROLLER_CONF_REPORT, "SCENE_CONTROLLER_CONF_REPORT"},
		{SCENE_CONTROLLER_CONF_SET, "SCENE_CONTROLLER_CONF_SET"}
		}},
	{COMMAND_CLASS_SCHEDULE_ENTRY_LOCK, "COMMAND_CLASS_SCHEDULE_ENTRY_LOCK", {
		{SCHEDULE_ENTRY_LOCK_ENABLE_ALL_SET, "SCHEDULE_ENTRY_LOCK_ENABLE_ALL_SET"},
		{SCHEDULE_ENTRY_LOCK_ENABLE_SET, "SCHEDULE_ENTRY_LOCK_ENABLE_SET"},
		{SCHEDULE_ENTRY_LOCK_WEEK_DAY_GET, "SCHEDULE_ENTRY_LOCK_WEEK_DAY_GET"},
		{SCHEDULE_ENTRY_LOCK_WEEK_DAY_REPORT, "SCHEDULE_ENTRY_LOCK_WEEK_DAY_REPORT"},
		{SCHEDULE_ENTRY_LOCK_WEEK_DAY_SET, "SCHEDULE_ENTRY_LOCK_WEEK_DAY_SET"},
		{SCHEDULE_ENTRY_LOCK_YEAR_DAY_GET, "SCHEDULE_ENTRY_LOCK_YEAR_DAY_GET"},
		{SCHEDULE_ENTRY_LOCK_YEAR_DAY_REPORT, "SCHEDULE_ENTRY_LOCK_YEAR_DAY_REPORT"},
		{SCHEDULE_ENTRY_LOCK_YEAR_DAY_SET, "SCHEDULE_ENTRY_LOCK_YEAR_DAY_SET"},
		{SCHEDULE_ENTRY_TYPE_SUPPORTED_GET, "SCHEDULE_ENTRY_TYPE_SUPPORTED_GET"},
		{SCHEDULE_ENTRY_TYPE_SUPPORTED_REPORT, "SCHEDULE_ENTRY_TYPE_SUPPORTED_REPORT"},
		{SCHEDULE_ENTRY_LOCK_TIME_OFFSET_GET_V2, "SCHEDULE_ENTRY_LOCK_TIME_OFFSET_GET"},
		{SCHEDULE_ENTRY_LOCK_TIME_OFFSET_REPORT_V2, "SCHEDULE_ENTRY_LOCK_TIME_OFFSET_REPORT"},
		{SCHEDULE_ENTRY_LOCK_TIME_OFFSET_SET_V2, "SCHEDULE_ENTRY_LOCK_TIME_OFFSET_SET"},
		{SCHEDULE_ENTRY_LOCK_DAILY_REPEATING_GET_V3, "SCHEDULE_ENTRY_LOCK_DAILY_REPEATING_GET"},
		{SCHEDULE_ENTRY_LOCK_DAILY_REPEATING_REPORT_V3, "SCHEDULE_ENTRY_LOCK_DAILY_REPEATING_REPORT"},
		{SCHEDULE_ENTRY_LOCK_DAILY_REPEATING_SET_V3, "SCHEDULE_ENTRY_LOCK_DAILY_REPEATING_SET"}
		}},
	{COMMAND_CLASS_SCREEN_ATTRIBUTES, "COMMAND_CLASS_SCREEN_ATTRIBUTES", {
		{SCREEN_ATTRIBUTES_GET, "SCREEN_ATTRIBUTES_GET"},
		{SCREEN_ATTRIBUTES_REPORT, "SCREEN_ATTRIBUTES_REPORT"},
		{SCREEN_ATTRIBUTES_REPORT, "SCREEN_ATTRIBUTES_REPORT"}
		}},
	{COMMAND_CLASS_SCREEN_MD, "COMMAND_CLASS_SCREEN_MD", {
		{SCREEN_MD_GET, "SCREEN_MD_GET"},
		{SCREEN_MD_REPORT, "SCREEN_MD_REPORT"},
		{SCREEN_MD_REPORT, "SCREEN_MD_REPORT"}
		}},
	{COMMAND_CLASS_SECURITY_PANEL_MODE, "COMMAND_CLASS_SECURITY_PANEL_MODE", {
		{SECURITY_PANEL_MODE_GET, "SECURITY_PANEL_MODE_GET"},
		{SECURITY_PANEL_MODE_REPORT, "SECURITY_PANEL_MODE_REPORT"},
		{SECURITY_PANEL_MODE_SET, "SECURITY_PANEL_MODE_SET"},
		{SECURITY_PANEL_MODE_SUPPORTED_GET, "SECURITY_PANEL_MODE_SUPPORTED_GET"},
		{SECURITY_PANEL_MODE_SUPPORTED_REPORT, "SECURITY_PANEL_MODE_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_SECURITY_PANEL_ZONE_SENSOR, "COMMAND_CLASS_SECURITY_PANEL_ZONE_SENSOR", {
		{COMMAND_CLASS_SECURITY_PANEL_ZONE_SENSOR_INSTALLED_REPORT, "COMMAND_CLASS_SECURITY_PANEL_ZONE_SENSOR_INSTALLED_REPORT"},
		{SECURITY_PANEL_ZONE_SENSOR_TYPE_GET, "SECURITY_PANEL_ZONE_SENSOR_TYPE_GET"},
		{SECURITY_PANEL_ZONE_SENSOR_TYPE_REPORT, "SECURITY_PANEL_ZONE_SENSOR_TYPE_REPORT"},
		{SECURITY_PANEL_ZONE_SENSOR_INSTALLED_GET, "SECURITY_PANEL_ZONE_SENSOR_INSTALLED_GET"},
		{SECURITY_PANEL_ZONE_SENSOR_STATE_GET, "SECURITY_PANEL_ZONE_SENSOR_STATE_GET"},
		{SECURITY_PANEL_ZONE_SENSOR_STATE_REPORT, "SECURITY_PANEL_ZONE_SENSOR_STATE_REPORT"}
		}},
	{COMMAND_CLASS_SECURITY_PANEL_ZONE, "COMMAND_CLASS_SECURITY_PANEL_ZONE", {
		{SECURITY_PANEL_ZONE_NUMBER_SUPPORTED_GET, "SECURITY_PANEL_ZONE_NUMBER_SUPPORTED_GET"},
		{SECURITY_PANEL_ZONE_STATE_GET, "SECURITY_PANEL_ZONE_STATE_GET"},
		{SECURITY_PANEL_ZONE_STATE_REPORT, "SECURITY_PANEL_ZONE_STATE_REPORT"},
		{SECURITY_PANEL_ZONE_SUPPORTED_REPORT, "SECURITY_PANEL_ZONE_SUPPORTED_REPORT"},
		{SECURITY_PANEL_ZONE_TYPE_GET, "SECURITY_PANEL_ZONE_TYPE_GET"},
		{SECURITY_PANEL_ZONE_TYPE_REPORT, "SECURITY_PANEL_ZONE_TYPE_REPORT"}
		}},
	{COMMAND_CLASS_SECURITY, "COMMAND_CLASS_SECURITY", {
		{NETWORK_KEY_SET, "NETWORK_KEY_SET"},
		{NETWORK_KEY_VERIFY, "NETWORK_KEY_VERIFY"},
		{SECURITY_COMMANDS_SUPPORTED_GET, "SECURITY_COMMANDS_SUPPORTED_GET"},
		{SECURITY_COMMANDS_SUPPORTED_REPORT, "SECURITY_COMMANDS_SUPPORTED_REPORT"},
		{SECURITY_MESSAGE_ENCAPSULATION, "SECURITY_MESSAGE_ENCAPSULATION"},
		{SECURITY_MESSAGE_ENCAPSULATION_NONCE_GET, "SECURITY_MESSAGE_ENCAPSULATION_NONCE_GET"},
		{SECURITY_NONCE_GET, "SECURITY_NONCE_GET"},
		{SECURITY_NONCE_REPORT, "SECURITY_NONCE_REPORT"},
		{SECURITY_SCHEME_GET, "SECURITY_SCHEME_GET"},
		{SECURITY_SCHEME_INHERIT, "SECURITY_SCHEME_INHERIT"},
		{SECURITY_SCHEME_REPORT, "SECURITY_SCHEME_REPORT"}
		}},
	{COMMAND_CLASS_SENSOR_ALARM, "COMMAND_CLASS_SENSOR_ALARM", {
		{SENSOR_ALARM_GET, "SENSOR_ALARM_GET"},
		{SENSOR_ALARM_REPORT, "SENSOR_ALARM_REPORT"},
		{SENSOR_ALARM_SUPPORTED_GET, "SENSOR_ALARM_SUPPORTED_GET"},
		{SENSOR_ALARM_SUPPORTED_REPORT, "SENSOR_ALARM_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_SENSOR_BINARY, "COMMAND_CLASS_SENSOR_BINARY", {
		{SENSOR_BINARY_GET, "SENSOR_BINARY_GET"},
		{SENSOR_BINARY_REPORT, "SENSOR_BINARY_REPORT"},
		{SENSOR_BINARY_SUPPORTED_GET_SENSOR_V2, "SENSOR_BINARY_SUPPORTED_GET_SENSOR"},
		{SENSOR_BINARY_SUPPORTED_SENSOR_REPORT_V2, "SENSOR_BINARY_SUPPORTED_SENSOR_REPORT"}
		}},
	{COMMAND_CLASS_SENSOR_CONFIGURATION, "COMMAND_CLASS_SENSOR_CONFIGURATION", {
		{SENSOR_TRIGGER_LEVEL_GET, "SENSOR_TRIGGER_LEVEL_GET"},
		{SENSOR_TRIGGER_LEVEL_REPORT, "SENSOR_TRIGGER_LEVEL_REPORT"},
		{SENSOR_TRIGGER_LEVEL_SET, "SENSOR_TRIGGER_LEVEL_SET"}
		}},
	{COMMAND_CLASS_SENSOR_MULTILEVEL, "COMMAND_CLASS_SENSOR_MULTILEVEL", {
		{SENSOR_MULTILEVEL_GET, "SENSOR_MULTILEVEL_GET"},
		{SENSOR_MULTILEVEL_REPORT, "SENSOR_MULTILEVEL_REPORT"},
		{SENSOR_MULTILEVEL_SUPPORTED_GET_SENSOR_V5, "SENSOR_MULTILEVEL_SUPPORTED_GET_SENSOR"},
		{SENSOR_MULTILEVEL_SUPPORTED_SENSOR_REPORT_V5, "SENSOR_MULTILEVEL_SUPPORTED_SENSOR_REPORT"},
		{SENSOR_MULTILEVEL_SUPPORTED_GET_SCALE_V5, "SENSOR_MULTILEVEL_SUPPORTED_GET_SCALE"},
		{SENSOR_MULTILEVEL_SUPPORTED_SCALE_REPORT_V5, "SENSOR_MULTILEVEL_SUPPORTED_SCALE_REPORT"}
		}},
	{COMMAND_CLASS_SILENCE_ALARM, "COMMAND_CLASS_SILENCE_ALARM", {
		{SENSOR_ALARM_SET, "SENSOR_ALARM_SET"}
		}},
	{COMMAND_CLASS_SIMPLE_AV_CONTROL, "COMMAND_CLASS_SIMPLE_AV_CONTROL", {
		{SIMPLE_AV_CONTROL_GET, "SIMPLE_AV_CONTROL_GET"},
		{SIMPLE_AV_CONTROL_REPORT, "SIMPLE_AV_CONTROL_REPORT"},
		{SIMPLE_AV_CONTROL_SET, "SIMPLE_AV_CONTROL_SET"},
		{SIMPLE_AV_CONTROL_SUPPORTED_GET, "SIMPLE_AV_CONTROL_SUPPORTED_GET"},
		{SIMPLE_AV_CONTROL_SUPPORTED_REPORT, "SIMPLE_AV_CONTROL_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_SWITCH_ALL, "COMMAND_CLASS_SWITCH_ALL", {
		{SWITCH_ALL_GET, "SWITCH_ALL_GET"},
		{SWITCH_ALL_OFF, "SWITCH_ALL_OFF"},
		{SWITCH_ALL_ON, "SWITCH_ALL_ON"},
		{SWITCH_ALL_REPORT, "SWITCH_ALL_REPORT"},
		{SWITCH_ALL_SET, "SWITCH_ALL_SET"}
		}},
	{COMMAND_CLASS_SWITCH_BINARY, "COMMAND_CLASS_SWITCH_BINARY", {
		{SWITCH_BINARY_GET, "SWITCH_BINARY_GET"},
		{SWITCH_BINARY_REPORT, "SWITCH_BINARY_REPORT"},
		{SWITCH_BINARY_SET, "SWITCH_BINARY_SET"}
		}},
	{COMMAND_CLASS_SWITCH_MULTILEVEL, "COMMAND_CLASS_SWITCH_MULTILEVEL", {
		{SWITCH_MULTILEVEL_GET, "SWITCH_MULTILEVEL_GET"},
		{SWITCH_MULTILEVEL_REPORT, "SWITCH_MULTILEVEL_REPORT"},
		{SWITCH_MULTILEVEL_SET, "SWITCH_MULTILEVEL_SET"},
		{SWITCH_MULTILEVEL_START_LEVEL_CHANGE, "SWITCH_MULTILEVEL_START_LEVEL_CHANGE"},
		{SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE, "SWITCH_MULTILEVEL_STOP_LEVEL_CHANGE"},
		{SWITCH_MULTILEVEL_SUPPORTED_GET_V3, "SWITCH_MULTILEVEL_SUPPORTED_GET"},
		{SWITCH_MULTILEVEL_SUPPORTED_REPORT_V3, "SWITCH_MULTILEVEL_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_SWITCH_COLOR, "COMMAND_CLASS_SWITCH_COLOR", {
		{SWITCH_COLOR_GET, "SWITCH_COLOR_GET"},
		{SWITCH_COLOR_REPORT, "SWITCH_COLOR_REPORT"},
		{SWITCH_COLOR_SET, "SWITCH_COLOR_SET"},
		{SWITCH_COLOR_START_LEVEL_CHANGE, "SWITCH_COLOR_START_LEVEL_CHANGE"},
		{SWITCH_COLOR_STOP_LEVEL_CHANGE, "SWITCH_COLOR_STOP_LEVEL_CHANGE"},
		{SWITCH_COLOR_SUPPORTED_GET, "SWITCH_COLOR_SUPPORTED_GET"},
		{SWITCH_COLOR_SUPPORTED_REPORT, "SWITCH_COLOR_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_SWITCH_TOGGLE_BINARY, "COMMAND_CLASS_SWITCH_TOGGLE_BINARY", {
		{SWITCH_TOGGLE_BINARY_SET, "SWITCH_TOGGLE_BINARY_SET"},
		{SWITCH_TOGGLE_BINARY_GET, "SWITCH_TOGGLE_BINARY_GET"},
		{SWITCH_TOGGLE_BINARY_REPORT, "SWITCH_TOGGLE_BINARY_REPORT"}
		}},
	{COMMAND_CLASS_SWITCH_TOGGLE_MULTILEVEL, "COMMAND_CLASS_SWITCH_TOGGLE_MULTILEVEL", {
		{SWITCH_TOGGLE_MULTILEVEL_SET, "SWITCH_TOGGLE_MULTILEVEL_SET"},
		{SWITCH_TOGGLE_MULTILEVEL_GET, "SWITCH_TOGGLE_MULTILEVEL_GET"},
		{SWITCH_TOGGLE_MULTILEVEL_REPORT, "SWITCH_TOGGLE_MULTILEVEL_REPORT"},
		{SWITCH_TOGGLE_MULTILEVEL_START_LEVEL_CHANGE, "SWITCH_TOGGLE_MULTILEVEL_START_LEVEL_CHANGE"},
		{SWITCH_TOGGLE_MULTILEVEL_STOP_LEVEL_CHANGE, "SWITCH_TOGGLE_MULTILEVEL_STOP_LEVEL_CHANGE"}
		}},
	{COMMAND_CLASS_TARIFF_CONFIG, "COMMAND_CLASS_TARIFF_CONFIG", {
		{TARIFF_TBL_REMOVE, "TARIFF_TBL_REMOVE"},
		{TARIFF_TBL_SET, "TARIFF_TBL_SET"},
		{TARIFF_TBL_SUPPLIER_SET, "TARIFF_TBL_SUPPLIER_SET"}
		}},
	{COMMAND_CLASS_TARIFF_TBL_MONITOR, "COMMAND_CLASS_TARIFF_TBL_MONITOR", {
		{TARIFF_TBL_COST_GET, "TARIFF_TBL_COST_GET"},
		{TARIFF_TBL_COST_REPORT, "TARIFF_TBL_COST_REPORT"},
		{TARIFF_TBL_GET, "TARIFF_TBL_GET"},
		{TARIFF_TBL_REPORT, "TARIFF_TBL_REPORT"},
		{TARIFF_TBL_SUPPLIER_GET, "TARIFF_TBL_SUPPLIER_GET"},
		{TARIFF_TBL_SUPPLIER_REPORT, "TARIFF_TBL_SUPPLIER_REPORT"}
		}},
	{COMMAND_CLASS_THERMOSTAT_FAN_MODE, "COMMAND_CLASS_THERMOSTAT_FAN_MODE", {
		{THERMOSTAT_FAN_MODE_GET, "THERMOSTAT_FAN_MODE_GET"},
		{THERMOSTAT_FAN_MODE_REPORT, "THERMOSTAT_FAN_MODE_REPORT"},
		{THERMOSTAT_FAN_MODE_SET, "THERMOSTAT_FAN_MODE_SET"},
		{THERMOSTAT_FAN_MODE_SUPPORTED_GET, "THERMOSTAT_FAN_MODE_SUPPORTED_GET"},
		{THERMOSTAT_FAN_MODE_SUPPORTED_REPORT, "THERMOSTAT_FAN_MODE_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_THERMOSTAT_FAN_STATE, "COMMAND_CLASS_THERMOSTAT_FAN_STATE", {
		{THERMOSTAT_FAN_STATE_GET, "THERMOSTAT_FAN_STATE_GET"},
		{THERMOSTAT_FAN_STATE_REPORT, "THERMOSTAT_FAN_STATE_REPORT"}
		}},
	{COMMAND_CLASS_THERMOSTAT_HEATING, "COMMAND_CLASS_THERMOSTAT_HEATING", {
		{THERMOSTAT_HEATING_STATUS_REPORT, "THERMOSTAT_HEATING_STATUS_REPORT"},
		{THERMOSTAT_HEATING_MODE_GET, "THERMOSTAT_HEATING_MODE_GET"},
		{THERMOSTAT_HEATING_MODE_REPORT, "THERMOSTAT_HEATING_MODE_REPORT"},
		{THERMOSTAT_HEATING_MODE_SET, "THERMOSTAT_HEATING_MODE_SET"},
		{THERMOSTAT_HEATING_RELAY_STATUS_GET, "THERMOSTAT_HEATING_RELAY_STATUS_GET"},
		{THERMOSTAT_HEATING_RELAY_STATUS_REPORT, "THERMOSTAT_HEATING_RELAY_STATUS_REPORT"},
		{THERMOSTAT_HEATING_SETPOINT_GET, "THERMOSTAT_HEATING_SETPOINT_GET"},
		{THERMOSTAT_HEATING_SETPOINT_REPORT, "THERMOSTAT_HEATING_SETPOINT_REPORT"},
		{THERMOSTAT_HEATING_SETPOINT_SET, "THERMOSTAT_HEATING_SETPOINT_SET"},
		{THERMOSTAT_HEATING_STATUS_GET, "THERMOSTAT_HEATING_STATUS_GET"},
		{THERMOSTAT_HEATING_STATUS_SET, "THERMOSTAT_HEATING_STATUS_SET"},
		{THERMOSTAT_HEATING_TIMED_OFF_SET, "THERMOSTAT_HEATING_TIMED_OFF_SET"}
		}},
	{COMMAND_CLASS_THERMOSTAT_MODE, "COMMAND_CLASS_THERMOSTAT_MODE", {
		{THERMOSTAT_MODE_GET, "THERMOSTAT_MODE_GET"},
		{THERMOSTAT_MODE_REPORT, "THERMOSTAT_MODE_REPORT"},
		{THERMOSTAT_MODE_SET, "THERMOSTAT_MODE_SET"},
		{THERMOSTAT_MODE_SUPPORTED_GET, "THERMOSTAT_MODE_SUPPORTED_GET"},
		{THERMOSTAT_MODE_SUPPORTED_REPORT, "THERMOSTAT_MODE_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_THERMOSTAT_OPERATING_STATE, "COMMAND_CLASS_THERMOSTAT_OPERATING_STATE", {
		{THERMOSTAT_OPERATING_STATE_GET, "THERMOSTAT_OPERATING_STATE_GET"},
		{THERMOSTAT_OPERATING_STATE_REPORT, "THERMOSTAT_OPERATING_STATE_REPORT"},
		{THERMOSTAT_OPERATING_STATE_LOGGING_SUPPORTED_GET_V2, "THERMOSTAT_OPERATING_STATE_LOGGING_SUPPORTED_GET"},
		{THERMOSTAT_OPERATING_LOGGING_SUPPORTED_REPORT_V2, "THERMOSTAT_OPERATING_LOGGING_SUPPORTED_REPORT"},
		{THERMOSTAT_OPERATING_STATE_LOGGING_GET_V2, "THERMOSTAT_OPERATING_STATE_LOGGING_GET"},
		{THERMOSTAT_OPERATING_STATE_LOGGING_REPORT_V2, "THERMOSTAT_OPERATING_STATE_LOGGING_REPORT"}
		}},
	{COMMAND_CLASS_THERMOSTAT_SETBACK, "COMMAND_CLASS_THERMOSTAT_SETBACK", {
		{THERMOSTAT_SETBACK_GET, "THERMOSTAT_SETBACK_GET"},
		{THERMOSTAT_SETBACK_REPORT, "THERMOSTAT_SETBACK_REPORT"},
		{THERMOSTAT_SETBACK_SET, "THERMOSTAT_SETBACK_SET"}
		}},
	{COMMAND_CLASS_THERMOSTAT_SETPOINT, "COMMAND_CLASS_THERMOSTAT_SETPOINT", {
		{THERMOSTAT_SETPOINT_GET, "THERMOSTAT_SETPOINT_GET"},
		{THERMOSTAT_SETPOINT_REPORT, "THERMOSTAT_SETPOINT_REPORT"},
		{THERMOSTAT_SETPOINT_SET, "THERMOSTAT_SETPOINT_SET"},
		{THERMOSTAT_SETPOINT_SUPPORTED_GET, "THERMOSTAT_SETPOINT_SUPPORTED_GET"},
		{THERMOSTAT_SETPOINT_SUPPORTED_REPORT, "THERMOSTAT_SETPOINT_SUPPORTED_REPORT"}
		}},
	{COMMAND_CLASS_TIME_PARAMETERS, "COMMAND_CLASS_TIME_PARAMETERS", {
		{TIME_PARAMETERS_GET, "TIME_PARAMETERS_GET"},
		{TIME_PARAMETERS_REPORT, "TIME_PARAMETERS_REPORT"},
		{TIME_PARAMETERS_SET, "TIME_PARAMETERS_SET"}
		}},
	{COMMAND_CLASS_TIME, "COMMAND_CLASS_TIME", {
		{DATE_GET, "DATE_GET"},
		{DATE_REPORT, "DATE_REPORT"},
		{TIME_GET, "TIME_GET"},
		{TIME_REPORT, "TIME_REPORT"},
		{TIME_OFFSET_GET_V2, "TIME_OFFSET_GET"},
		{TIME_OFFSET_REPORT_V2, "TIME_OFFSET_REPORT"},
		{TIME_OFFSET_SET_V2, "TIME_OFFSET_SET"}
		}},
	{COMMAND_CLASS_TRANSPORT_SERVICE, "COMMAND_CLASS_TRANSPORT_SERVICE", {
		{COMMAND_FIRST_FRAGMENT, "COMMAND_FIRST_FRAGMENT"},
		//{COMMAND_FRAGMENT_COMPLETE, "COMMAND_FRAGMENT_COMPLETE"},
		//{COMMAND_FRAGMENT_REQUEST, "COMMAND_FRAGMENT_REQUEST"},
		//{COMMAND_FRAGMENT_WAIT, "COMMAND_FRAGMENT_WAIT"},
		{COMMAND_SUBSEQUENT_FRAGMENT, "COMMAND_SUBSEQUENT_FRAGMENT"}
		}},
	{COMMAND_CLASS_USER_CODE, "COMMAND_CLASS_USER_CODE", {
		{USER_CODE_GET, "USER_CODE_GET"},
		{USER_CODE_REPORT, "USER_CODE_REPORT"},
		{USER_CODE_SET, "USER_CODE_SET"},
		{USERS_NUMBER_GET, "USERS_NUMBER_GET"},
		{USERS_NUMBER_REPORT, "USERS_NUMBER_REPORT"}
		}},
	{COMMAND_CLASS_BARRIER_OPERATOR, "COMMAND_CLASS_BARRIER_OPERATOR",{
		{BARRIER_OPERATOR_GET, "BARRIER_OPERATOR_GET" },
		{BARRIER_OPERATOR_REPORT, "BARRIER_OPERATOR_REPORT" },
		{BARRIER_OPERATOR_SET, "BARRIER_OPERATOR_SET" },
		{BARRIER_OPERATOR_SIGNAL_GET, "BARRIER_OPERATOR_SUBSYSTEM_GET" },
		{BARRIER_OPERATOR_SIGNAL_REPORT, "BARRIER_OPERATOR_SUBSYSTEM_REPORT" },
		{BARRIER_OPERATOR_SIGNAL_SET, "BARRIER_OPERATOR_SUBSYSTEM_SET" },
		{BARRIER_OPERATOR_SIGNAL_SUPPORTED_GET, "BARRIER_OPERATOR_SUBSYSTEM_SUPPORTED_GET" },
		{BARRIER_OPERATOR_SIGNAL_SUPPORTED_REPORT, "BARRIER_OPERATOR_SUBSYSTEM_SUPPORTED_REPORT" }
		}},
	{COMMAND_CLASS_VERSION, "COMMAND_CLASS_VERSION", {
		{VERSION_COMMAND_CLASS_GET, "VERSION_COMMAND_CLASS_GET"},
		{VERSION_COMMAND_CLASS_REPORT, "VERSION_COMMAND_CLASS_REPORT"},
		{VERSION_GET, "VERSION_GET"},
		{VERSION_REPORT, "VERSION_REPORT"}
		}},
	{COMMAND_CLASS_WAKE_UP, "COMMAND_CLASS_WAKE_UP", {
		{WAKE_UP_INTERVAL_GET, "WAKE_UP_INTERVAL_GET"},
		{WAKE_UP_INTERVAL_REPORT, "WAKE_UP_INTERVAL_REPORT"},
		{WAKE_UP_INTERVAL_SET, "WAKE_UP_INTERVAL_SET"},
		{WAKE_UP_NO_MORE_INFORMATION, "WAKE_UP_NO_MORE_INFORMATION"},
		{WAKE_UP_NOTIFICATION, "WAKE_UP_NOTIFICATION"},
		{WAKE_UP_INTERVAL_CAPABILITIES_GET_V2, "WAKE_UP_INTERVAL_CAPABILITIES_GET"},
		{WAKE_UP_INTERVAL_CAPABILITIES_REPORT_V2, "WAKE_UP_INTERVAL_CAPABILITIES_REPORT"}
		}},
	{COMMAND_CLASS_ZIP_6LOWPAN, "COMMAND_CLASS_ZIP_6LOWPAN", {
		{LOWPAN_FIRST_FRAGMENT, "LOWPAN_FIRST_FRAGMENT"},
		{LOWPAN_SUBSEQUENT_FRAGMENT, "LOWPAN_SUBSEQUENT_FRAGMENT"}
		}},
	{COMMAND_CLASS_ZIP, "COMMAND_CLASS_ZIP", {
		{COMMAND_ZIP_PACKET, "COMMAND_ZIP_PACKET"}
		}},
	{COMMAND_CLASS_APPLICATION_CAPABILITY, "COMMAND_CLASS_APPLICATION_CAPABILITY", {
		{COMMAND_COMMAND_CLASS_NOT_SUPPORTED, "COMMAND_COMMAND_CLASS_NOT_SUPPORTED"}
		}},
	{COMMAND_CLASS_SWITCH_COLOR, "COMMAND_CLASS_SWITCH_COLOR", {
		{SWITCH_COLOR_SUPPORTED_GET, "SWITCH_COLOR_SUPPORTED_GET"},
		{SWITCH_COLOR_SUPPORTED_REPORT, "SWITCH_COLOR_SUPPORTED_REPORT"},
		{SWITCH_COLOR_GET, "SWITCH_COLOR_GET"},
		{SWITCH_COLOR_REPORT, "SWITCH_COLOR_REPORT"},
		{SWITCH_COLOR_SET, "SWITCH_COLOR_SET"},
		{SWITCH_COLOR_START_LEVEL_CHANGE, "SWITCH_COLOR_START_LEVEL_CHANGE"},
		{SWITCH_COLOR_STOP_LEVEL_CHANGE, "SWITCH_COLOR_STOP_LEVEL_CHANGE"}
		}},
	{COMMAND_CLASS_SCHEDULE, "COMMAND_CLASS_SCHEDULE", {
		{SCHEDULE_SUPPORTED_GET, "SCHEDULE_SUPPORTED_GET"},
		{SCHEDULE_SUPPORTED_REPORT, "SCHEDULE_SUPPORTED_REPORT"},
		{COMMAND_SCHEDULE_SET, "COMMAND_SCHEDULE_SET"},
		{COMMAND_SCHEDULE_GET, "COMMAND_SCHEDULE_GET"},
		{COMMAND_SCHEDULE_REPORT, "COMMAND_SCHEDULE_REPORT"},
		{SCHEDULE_REMOVE, "SCHEDULE_REMOVE"},
		{SCHEDULE_STATE_SET, "SCHEDULE_STATE_SET"},
		{SCHEDULE_STATE_GET, "SCHEDULE_STATE_GET"},
		{SCHEDULE_STATE_REPORT, "SCHEDULE_STATE_REPORT"}
		}},
	{COMMAND_CLASS_NETWORK_MANAGEMENT_PRIMARY, "COMMAND_CLASS_NETWORK_MANAGEMENT_PRIMARY", {
		{CONTROLLER_CHANGE, "CONTROLLER_CHANGE"},
		{CONTROLLER_CHANGE_STATUS, "CONTROLLER_CHANGE_STATUS"}
		}},
	{COMMAND_CLASS_ZIP_ND, "COMMAND_CLASS_ZIP_ND", {
		{ZIP_NODE_SOLICITATION, "ZIP_NODE_SOLICITATION"},
		{ZIP_INV_NODE_SOLICITATION, "ZIP_INV_NODE_SOLICITATION"},
		{ZIP_NODE_ADVERTISEMENT, "ZIP_NODE_ADVERTISEMENT"}
		}},
	{COMMAND_CLASS_ASSOCIATION_GRP_INFO, "COMMAND_CLASS_ASSOCIATION_GRP_INFO", {
		{ASSOCIATION_GROUP_NAME_GET, "ASSOCIATION_GROUP_NAME_GET"},
		{ASSOCIATION_GROUP_NAME_REPORT, "ASSOCIATION_GROUP_NAME_REPORT"},
		{ASSOCIATION_GROUP_INFO_GET, "ASSOCIATION_GROUP_INFO_GET"},
		{ASSOCIATION_GROUP_INFO_REPORT, "ASSOCIATION_GROUP_INFO_REPORT"},
		{ASSOCIATION_GROUP_COMMAND_LIST_GET, "ASSOCIATION_GROUP_COMMAND_LIST_GET"},
		{ASSOCIATION_GROUP_COMMAND_LIST_REPORT, "ASSOCIATION_GROUP_COMMAND_LIST_REPORT"}
		}},
	{COMMAND_CLASS_DEVICE_RESET_LOCALLY, "COMMAND_CLASS_DEVICE_RESET_LOCALLY", {
		{DEVICE_RESET_LOCALLY_NOTIFICATION, "DEVICE_RESET_LOCALLY_NOTIFICATION"}
		}},
	{COMMAND_CLASS_CENTRAL_SCENE, "COMMAND_CLASS_CENTRAL_SCENE", {
		{CENTRAL_SCENE_SUPPORTED_GET, "CENTRAL_SCENE_SUPPORTED_GET"},
		{CENTRAL_SCENE_SUPPORTED_REPORT, "CENTRAL_SCENE_SUPPORTED_REPORT"},
		{CENTRAL_SCENE_NOTIFICATION, "CENTRAL_SCENE_NOTIFICATION"}
		}},
	{COMMAND_CLASS_IP_ASSOCIATION, "COMMAND_CLASS_IP_ASSOCIATION", {
		{IP_ASSOCIATION_SET, "IP_ASSOCIATION_SET"},
		{IP_ASSOCIATION_GET, "IP_ASSOCIATION_GET"},
		{IP_ASSOCIATION_REPORT, "IP_ASSOCIATION_REPORT"},
		{IP_ASSOCIATION_REMOVE, "IP_ASSOCIATION_REMOVE"}
		}},
	{COMMAND_CLASS_ANTITHEFT, "COMMAND_CLASS_ANTITHEFT", {
		{ANTITHEFT_SET, "ANTITHEFT_SET"},
		{ANTITHEFT_GET, "ANTITHEFT_GET"},
		{ANTITHEFT_REPORT, "ANTITHEFT_REPORT"}
		}},
#ifdef COMMAND_CLASS_ZIP_GATEWAY
	{COMMAND_CLASS_ZIP_GATEWAY, "COMMAND_CLASS_ZIP_GATEWAY", {
#ifdef UNSOLICITED_DESTINATION_SET
		{UNSOLICITED_DESTINATION_SET, "UNSOLICITED_DESTINATION_SET"},
		{UNSOLICITED_DESTINATION_GET, "UNSOLICITED_DESTINATION_GET"},
		{UNSOLICITED_DESTINATION_REPORT, "UNSOLICITED_DESTINATION_REPORT"},
#endif
#ifdef COMMAND_APPLICATION_NODE_INFO_SET
		{COMMAND_APPLICATION_NODE_INFO_SET, "COMMAND_APPLICATION_NODE_INFO_SET"},
		{COMMAND_APPLICATION_NODE_INFO_GET, "COMMAND_APPLICATION_NODE_INFO_GET"},
		{COMMAND_APPLICATION_NODE_INFO_REPORT, "COMMAND_APPLICATION_NODE_INFO_REPORT"},
#endif
		{GATEWAY_MODE_SET, "GATEWAY_MODE_SET"},
		{GATEWAY_MODE_GET, "GATEWAY_MODE_GET"},
		{GATEWAY_MODE_REPORT, "GATEWAY_MODE_REPORT"},
		{GATEWAY_PEER_SET, "GATEWAY_PEER_SET"},
		{GATEWAY_PEER_GET, "GATEWAY_PEER_GET"},
		{GATEWAY_PEER_REPORT, "GATEWAY_PEER_REPORT"},
		{GATEWAY_LOCK_SET, "GATEWAY_LOCK_SET"}
		}},
#endif
#ifdef COMMAND_CLASS_ZIP_PORTAL
	{COMMAND_CLASS_ZIP_PORTAL, "COMMAND_CLASS_ZIP_PORTAL", {
		{GATEWAY_CONFIGURATION_SET, "GATEWAY_CONFIGURATION_SET"},
		{GATEWAY_CONFIGURATION_STATUS, "GATEWAY_CONFIGURATION_STATUS"},
		{GATEWAY_CONFIGURATION_GET, "GATEWAY_CONFIGURATION_GET"},
		{GATEWAY_CONFIGURATION_REPORT, "GATEWAY_CONFIGURATION_REPORT"}
		}},
#endif
	{COMMAND_CLASS_ZWAVEPLUS_INFO, "COMMAND_CLASS_ZWAVEPLUS_INFO", {
		{ZWAVEPLUS_INFO_GET, "ZWAVEPLUS_INFO_GET"},
		{ZWAVEPLUS_INFO_REPORT, "ZWAVEPLUS_INFO_REPORT"}
		}}
};

char *zwp_hcapi_zwave_command_class_to_string(uint16_t class_id, uint8_t class_version)
{
	int count;
	int i;
	char *string = NULL;

	count = sizeof(g_zwp_hcapi_zwave_command_class) / sizeof(g_zwp_hcapi_zwave_command_class[0]);

	string = "Unknown";
	for (i = 0; i < count; i++)
	{
		if (g_zwp_hcapi_zwave_command_class[i].class_id == class_id)
		{
			string = g_zwp_hcapi_zwave_command_class[i].class_name;
			break;
		}
	}

	if (class_id == COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION_V2)
	{
		string = (class_version >= 2) ? "COMMAND_CLASS_MULTI_CHANNEL_ASSOCIATION" : "COMMAND_CLASS_MULTI_INSTANCE_ASSOCIATION";
	}
	else if (class_id == COMMAND_CLASS_MULTI_CHANNEL_V2)
	{
		string = (class_version >= 2) ? "COMMAND_CLASS_MULTI_CHANNEL" : "COMMAND_CLASS_MULTI_INSTANCE";
	}

	return string;
}

char *zwp_hcapi_zwave_command_to_string(uint16_t class_id, uint8_t command_id)
{
	int class_count;
	int command_count;
	int i;
	int j;
	char *string = NULL;

	class_count = sizeof(g_zwp_hcapi_zwave_command_class) / sizeof(g_zwp_hcapi_zwave_command_class[0]);

	command_count = sizeof(g_zwp_hcapi_zwave_command_class[0].command) / sizeof(*g_zwp_hcapi_zwave_command_class[0].command);

	string = "Unknown";
	for (i = 0; i < class_count; i++)
	{
		if (g_zwp_hcapi_zwave_command_class[i].class_id == class_id)
		{
			j = 0;

			while ((j < command_count) && (g_zwp_hcapi_zwave_command_class[i].command[j].command_id != 0))
			{
				if (g_zwp_hcapi_zwave_command_class[i].command[j].command_id == command_id)
				{
					string = g_zwp_hcapi_zwave_command_class[i].command[j].command_name;
					break;
				}
				j++;
			}
			break;
		}
	}

	return string;
}



