DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='5.3'
DISTRIB_REVISION='1.2'
DISTRIB_CODENAME='qca-spf-cs'
DISTRIB_TARGET='ipq806x/generic'
DISTRIB_DESCRIPTION='gemtek-qca-spf-cs'
DISTRIB_TAINTS='no-all busybox override'
DISTRIB_BUILD='TRQ44INDDURD-1.2'
