#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (C) 2009 Zensys
# Copyright (C) 2011 OpenWrt.org
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 11/05/2018
#====================================================================#

START=95
STOP=87

start() {
    # Start Z/IP Router as daemon:
    zipgateway -e /usr/share/z-wave/eeprom.dat &
}

stop() {
	killall zipgateway
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[ZW]: Zipgateway service stopped"
	else 
		logger -p user.crit "[ZW]: No Zipgateway service to stop"
	fi
}
