#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.2
# Last modified: janardhanachari.kella@smartron.com,nagendra@smartron.com 14/06/2018
#====================================================================#
. /tmp/updated

START=86
USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
                sleep 1;
        done
	logger -p user.notice "DM service starting"
        procd_open_instance
        procd_set_param command /exe_dir/DM_init
	procd_set_param respawn
        procd_close_instance
	logger -p user.crit "[DM]: Device Manager service started"
}

stop_service() {
	kill -9 `ps | grep Device_Manager_Gateway | grep -v grep | awk '{print $1}'`
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[DM]: Device Manager service stopped"
	else 
		logger -p user.crit "[DM]: No Device Manager service to stop"
	fi
}
