#!/bin/sh /etc/rc.common
#====================================================================#
# Copyright (c) 2013 The Linux Foundation. All rights reserved.
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 14/06/2018
#====================================================================#
START=92
STOP=15
USE_PROCD=1

start_service() {
	# Workaround get button error at first time
	i2cget -y 0 0x18 0x50 > /dev/null
        procd_open_instance
        procd_set_param command /usr/bin/hw-control
	procd_set_param respawn
        procd_close_instance
	logger -p user.crit "[HW]: Hardware Control service started"

}
stop_service() {
	killall hw-control
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[HW]: Hardware Control service stopped"
	else 
		logger -p user.crit "[HW]: No Hardware Control service to stop"
	fi
}
