#!/bin/sh /etc/rc.common
#=====================================================================================#
# Copyright (c) 2018 Smartron India Pvt. Ltd. All rights reserved.
# Version:0.3
# Last modified: nagendra@smartron.com, 11/09/2018
#=====================================================================================#

. /tmp/updated

START=85

USE_PROCD=1

start_service() {
	while [ "$UPDATED" != "1" ];do
		sleep 1;
	done

	logger -p user.notice "[MQTT]: MQTT Manager starting"
	procd_open_instance
	procd_set_param command /usr/sbin/mqtt-manager
	procd_set_param respawn
	procd_close_instance
	logger -p user.notice "[MQTT]: MQTT Manager started"
}

stop_service() {
	kill -9 mqtt-manager
	if [ "$?" = "0" ] ; then
		logger -p user.crit "[MQTT]: MQTT Manager service stopped"
	else 
		logger -p user.crit "[MQTT]: No MQTT Manager service to stop"
	fi
}
