portal:
{
	/** listen_port - Listening port of portal server */
	listen_port: 44123

	/** security - Security settings */
	security:
	{
		/** CA_certificate_file - CA certificate file location */
		CA_certificate_file =  "ZIPR.ca_x509.pem"

		/** SSL_certificate_file - SSL certificate file location */
		SSL_certificate_file = "Portal.x509_1024.cer"

		/** private_key_file - Private key file location */
		private_key_file = "Portal.key_1024"
	};

	/** device_specific_configuration_file - Device specific configuration file */
	device_specific_configuration_file = "zwave_device_rec.txt"

	/** network - Network settings */
	network:
	{
		interface:
		{
			/** report_wait_timeout - Maximum wait time (in seconds) to
			 * receive a Z-Wave Report command after sending a Z-Wave Get
			 * command. Applicable only for non-sleeping devices.
			 */
			report_wait_timeout = 11
		}
	}
};

server:
{
	/** thread_pool - Service thread pool settings */
	thread_pool:
	{
		/** thread_init_count - Initial thread count */
		thread_init_count = 10

		/** thread_max_count - Maximum thread count */
		thread_max_count = 50
	}
};

ldap:
{
	/** uri - LDAP URI */
	uri = "ldapi:///"

	/** bind - LDAP bind */
	bind:
	{
		/** type - type of bind
		 * "anonymous"    - bind mechanism is skipped
		 * "simple"       - simple bind
		 * "sasl"         - SASL bind (not supported yet)
		 */
		type = "simple"

		/** simple - configurations for simple bind */
		simple:
		{
			/** dn - bind DN */
			dn = "cn=Manager,<LDAP_BASE_DN>"

			/** password - bind password */
			password = "<LDAP_AUTH_PASSWORD>"
		}
	}

	/** base_dn - Base DN for all LDAP operations */
	base_dn = "<LDAP_BASE_DN>"
};

ifttt:
{
	/** channel_key - IFTTT channel key */
	channel_key = "<IFTTT_CHANNEL_KEY>"

	/** realtime_api_post_interval - IFTTT realtime API POST interval */
	realtime_api_post_interval = <IFTTT_REALTIME_API_POST_INTERVAL>

	/** realtime_api_post_retry - IFTTT realtime API POST retry */
	realtime_api_post_retry = <IFTTT_REALTIME_API_POST_RETRY>
};

log:
{
	/** upto_level - logging is restricted to this level and all other levels
	 * that are more important than this level. The following listing is in
	 * decreasing order of importance
	 * "emergency"    - system is unstable
	 * "alert"        - action must be taken immediately
	 * "critical"     - critical conditions
	 * "error"        - error conditions
	 * "warning"      - warning conditions
	 * "notice"       - normal, but significant condition
	 * "information"  - informational messsage
	 * "debug"        - debug-level message
	 */
	upto_level = "debug"

	/** target - target entity for logging
	 * "console"      - logs to the console (stdout and stderr)
	 * "syslog"       - uses system logger. If error, logs to the console
	 */
	target = "console"
};

local:
{
	/** gw_set_auto_local - set the gateway unsolicited ip address to local ip addr
		1 - Enable
		0 - Disable
	 **/
	gw_auto_set_to_local : 1
};
